### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#104]
After 2.1 is released we should start to define a plugin API. This might involve:

- documentation
- re-exporting officially public functions for plugins in a shim module
- breaking existing plugins. as there is no official plugin API yet, this may be inevitable, but should be avoided or handled with versioning and proper communication.

**Comment by tuncer** [comment]
@ferd has the rebar3 fork implemented this (including a built-in registry of well-known plugins to enable automatically)?

**Comment by tuncer** [comment]
@ferd has the rebar3 fork implemented this (including a built-in registry of well-known plugins to use if available and required)?

**Comment by ferd** [comment]
Not yet. We have the shim module (somewhat partial without enough warning) and docs, but no registry at this time; it's a task for beta/3.0.0.

**Comment by lrascao** [comment]
Is this still relevant given rebar3's advances in the meantime?

**Comment by ferd** [comment]
We do have a better-defined plugin API for rebar3, but I think it still needs expanding to avoid having people depend too much on the internals. I'm not sure how much we expect rebar 2.x's plugins to evolve in the upcoming years though. I'd say it's probably stable now.

**Comment by tuncer** [comment]
@ferd, that's what I intended a shim module to be for: define one or more plugin API modules which expose things in a stable fashion, leaving anything else as internal.

I'd say we can close this, but if rebar3's plugin API doesn't promise stability (yet), maybe we ought to wait with that.

**Comment by ferd** [comment]
Yes, we do have a `rebar_api` module, and that's what I meant by 'needs expanding'; adding functions to it. Closing this, as we should have stability by 3.0.0, which should be increasingly soon now.
