### ISSUE TITLE
retest project

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#180]
Should we maintain the retest project in the rebar org?

cc @dizzyd @jaredmorrow

**Comment by lrascao** [comment]
@dizzyd is no longer maintaining retest so it's not such a bad idea moving it to the rebar org

**Comment by tuncer** [comment]
@jaredmorrow, or whoever has the rights to do so, go ahead and add a fork at rebar/retest.

**Comment by lrascao** [comment]
Ideally @dizzyd could move it to the rebar org, if he agrees of course

**Comment by jaredmorrow** [comment]
It has been forked https://github.com/rebar/retest.  Someone can now go about updating the dep in rebar to point at the fork

**Comment by lrascao** [comment]
done
@jaredmorrow, could you please activate retest on Travis?

**Comment by tuncer** [comment]
Thanks.

**Comment by tuncer** [comment]
Resolved.
