### ISSUE TITLE
lock-deps command

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#181]
Let's discuss if and how to implement an integrated lock-deps command.

cc @seth @Vagabond @dizzyd @jaredmorrow

**Comment by lrascao** [comment]
https://github.com/seth/rebar_lock_deps_plugin does a good job of locking deps, my suggestion we advise people to use that instead of implementing it in rebar

**Comment by tuncer** [comment]
Sure, or alternatively, suggest rebar3 once it's restored some of the features that got lost in the refactoring.

**Comment by tsloughter** [comment]
rebar3 itself is, and has been for a while now, feature complete for the coming stable release of 3.0.

**Comment by tuncer** [comment]
From a certain perspective that's true, and I can understand that you might view some of the lost features unimportant. But, I would like to have only one active rebar version, and the removal of some features, as discussed in the past, prevents me from using or promoting rebar3. Eventually, we'll get there. If you'd like to discuss it (again), let's start a thread on the list.

**Comment by tsloughter** [comment]
Feel free to start a thread, I don't know what lost features you are referring to.

**Comment by tuncer** [comment]
Sure, will do.

**Comment by lrascao** [comment]
So i suppose this means we can close this ticket as well, right?

**Comment by tuncer** [comment]
Yes.
