### ISSUE TITLE
Adapt built-in port_env to support OS X Mavericks or newer

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#182]
Someone with access to OS X Mavericks or newer should adapt the built-in [port_env](https://github.com/rebar/rebar/blob/988c9cd574538d279193f548297d80ad3b0a45d0/src/rebar_port_compiler.erl#L579).

cc @jaredmorrow @Vagabond @dizzyd

**Comment by lrascao** [comment]
Fixed in #590
