### ISSUE TITLE
Differentiate between common and test-only deps

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#206]
Currently rebar has no way to differentiate between common and test-only deps ([original mailing list post](http://lists.basho.com/pipermail/rebar_lists.basho.com/2014-January/001995.html)). Let's design how such a distinction could be specified in a project's configuration and/or command line options.

Let's assume we have one of the following ways to express test-only deps.

#### A: Separate 'deps' and 'test_deps'
```erlang
{deps,
 [
  {lib, ".*", {git, "git://github.com/lib/lib.git"}}
 ]}.
{test_deps,
 [
  {meck, ".*", {git, "git://github.com/meck/meck.git"}}
 ]}.
```

#### B: 'test_deps' mixed in with common 'deps'
```erlang
{deps,
 [
  {lib, ".*", {git, "git://github.com/lib/lib.git"}},
  {meck, ".*", {git, "git://github.com/meck/meck.git"}, [test]}
 ]}.
```

How should this work in practice? Should the deps be fetched always but only added to the code path for certain commands? Should the test commands (ct, eunit, qc) trigger fetch+build of test-only deps?

Besides test-only deps, do we have to consider any other types of special dependencies?

cc @archaelus @seth @jaredmorrow @seancribbs @xenolinguist

**Comment by tuncer** [comment]
Given that this was implemented in the rebar3 fork, should we close this?

**Comment by ferd** [comment]
Works for me, yeah.
