### ISSUE TITLE
Implement real version constraint (sat) solver

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#240]
I think it's inevitable to eventually implement a real version constraint (sat) solver (e.g `>= 1.2.* && < 1.7.*`). The various require_*_vsn options and version strings in dependency specs do not cover all real world use cases. @thijsterlouw submitted a patch to implement semver vsn checking. Would that be universal enough, or would it limit what constraints are supported?

See #163 #222 basho/rebar#262 basho/rebar#263

**Comment by define-null** [comment]
Do I understand you correctly, that this feature will never be implemented in rebar and version constraints checking is not in your plans?

**Comment by ferd** [comment]
This could be attempted, but frankly I won't be the one to put time into it. An alternative approach (using distance from the root rather than versions) has been chosen for rebar3, which is where @tsloughter and others have been spending time trying to fix these things.

**Comment by tsloughter** [comment]
And there is no way without a package index would a sat solver work. Certainly not something that could be implemented on top of rebar2 without also adding support for some package repository.

So, safe to say rebar2 will never have a depsolver :)

**Comment by define-null** [comment]
If anyone is interested in vsn checking, i created small plugin for rebar (https://github.com/define-null/rebar_version_checker), to solve this task. It's can be still not mature enough, so any feedback is welcomed.

Ideas borrowed both from this thread and https://github.com/basho/rebar/pull/262

**Comment by tuncer** [comment]
@define-null, thanks for sharing. While this ticket is about a solver for constraints like `>= 1.2.* && < 1.7.*`, a simple solver for only `>= 1.2.*` seems like an improvement over the vsn regexes we have now. So, if this is what users want, and you submit a pull request. I don't mind integrating it as an alternative to regexes.

**Comment by tuncer** [comment]
@define-null, thanks for sharing. While this ticket is about a solver for constraints like `>= 1.2.* && < 1.7.*`, a simple solver for only `>= 1.2.*` seems like an improvement over the vsn regexes we have now. So, if this is what users want, and you submit a pull request, I would like for that to be integrated as an alternative to regexes.

**Comment by define-null** [comment]
Well, `>= 1.2.* && < 1.7.*` constrain can be written in terms of the plugin as `[">= 1.2.0", "< 1.7.0"]`. 
Don't know whether * should be allowed, or for example an option to exclude some intervals of versions..  i really don't think full regexp support if good for solving this tasks.

As for the pullrequest the plugin solve our compani's needs now, and separate section for version checking seems to be ok cause it does not violate old projects and it's easy to integrate.

I don't see better solution right now for constrain support without breaking compatability with old versions.

**Comment by tuncer** [comment]
@define-null, sounds good, and what about `||`?

`1.2.*` should mean the same as `1.2`, but I wouldn't mind not support `*`.

Also, of course the question remains what to compare against (index, vcs tags, ...). How do you use it at your company?

**Comment by tuncer** [comment]
Just to be clear, like I suggested in @psyeugenic's gears thread on erlang-questions, a proper solution requires integration in erts, stdlib, and kernel, in order to fully support this in apps and releases. Still, that doesn't mean a simple enhancement in rebar won't be useful.

**Comment by define-null** [comment]
@tuncer yes, plugin can be extended to use `||` and also '(' ')', but I also faced with the fact that 'git' tag versioning in rebar is not compatible with semver at all, and extra work should be done to treat 'git' tag in the other way. ( for example 0.6.0-5-g0c95039 < 0.6.0 in semver but in case of 'git' tag in rebar it means that 5 commits were created after 0.6.0 tag, so 0.6.0-5-g0c95039 should be always greater. I think 0.6.0-5-g0c95039 should look like 0.6.0+build.5.g0c95039 to be semver compatible )

Anyway if you have any suggestions please post an issue or send pullrequest to the github repo mentioned above.

**Comment by tuncer** [comment]
That's not a tag, so it doesn't have to be supported. Tags are created explicitly.

**Comment by nox** [comment]
> I think 0.6.0-5-g0c95039 should look like 0.6.0+build.5.g0c95039 to be semver compatible

And note that with this change, this version would still not be greater than 0.6.0 because build metadata isn't taken into consideration when comparing versions in semver.

**Comment by define-null** [comment]
@nox yeah, i know, but how to name the dev version after 0.6.0 which does not have breaking changes in semver without extra version?  It's ok for me that 0.6.0+build.5.g0c95039 at least not smaller then 0.6.0, better then nothing.. 

@tuncer sorry for my poor english, by the "git tag" i meant `{vsn, git}` approach in app.src. Of course anyone can use `{vsn, cmd}` instead to define his own versioning schema, but it would be great to have one, available in rebar, which support simple version constraints as discussed above. May be semver is not good enough for this.

**Comment by tuncer** [comment]
@define-null wrote:

> Personally I don't want ever to specify version explicitly in app.src, version should be generated based on the tag I added with git or other vcs,

You don't have to:
1. When the rev is a tag, this will be reflected correctly in your generated `.app`. This is the only scenario where listing tags and trying to solve the vsn constraint against that (because there's no index) will work.
2. If you do not want to depend on a specific tag, you will most likely ask for a branch, and therefore you will be best served with the regex vsn match.
3. If you do want to depend on a specific rev that isn't tagged yet, you will ask for that commit (rev) and again use the regex vsn match.

> Of course anyone can use {vsn, cmd} instead to define his own versioning schema, but it would be great to have one, available in rebar, which support simple version constraints as discussed above. May be semver is not good enough for this.

Yeah, as you can read above in the rpm versioning discussion, semver appears to be underspecified and insufficient.
