### ISSUE TITLE
rebar ct doesn't use app.config appropriately

### ISSUE THREAD

**Issue by rlipscombe** [rebar/rebar#241]
In rebar_ct.erl, make_cmd/3 creates a command line containing "-config app.config -ct_config test.config".

Since this change:

https://github.com/rebar/rebar/commit/9cf7cf7cb06e0f2546b3cd37be0a9f8566312fc4#diff-8fa99bb3b871b413798c098ae723a998R195

...this no longer works as expected: ct_run converts -config into -ct_config; this means that there doesn't appear to be a way to provide an app config to the tests.

**Comment by lrascao** [comment]
Closing as #411 has since been merged
