### ISSUE TITLE
rebar eunit doesn't compile .yrl files

### ISSUE THREAD

**Issue by kaos** [rebar/rebar#247]
Hi,

Either I'm missing something, or the eunit command fails to compile .yrl files when running the test suite.

When running `rebar eunit` on a clean project (i.e. no previously built beam files around), it fails due to a missing beam file that should've come from compiling a .yrl file (https://travis-ci.org/erlydtl/erlydtl/jobs/20463110).

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
