### ISSUE TITLE
recursively check git status

### ISSUE THREAD

**Issue by davidw** [rebar/rebar#264]
I've occasionally had it happen that I don't know which of my deps/ I've done work in (it's convenient to work there directly when hacking away).  This escript solves that.  It'd be nice if something similar were to find its way into rebar.  I'd be happy to try and put it together

```
#!/usr/bin/env escript

main(Dirs) ->
    Self = self(),
    [spawn(fun() ->
                   check_status(Dir, Self)
           end) || Dir <- Dirs],
    loop(length(Dirs)).

check_status(Dir, Parent) ->
    Cmd = io_lib:format("git ls-files --modified --deleted", []),
    Port = open_port({spawn, Cmd}, [{cd, Dir}, exit_status]),
    check_status_loop(Parent, Port, Dir).

check_status_loop(Parent, Port, Dir) ->
    receive
        {Port, {exit_status, _Status}} ->
            Parent ! ok;
        {Port, {data, Filename}} ->
            io:format("~s: ~s", [Dir, Filename]),
            check_status_loop(Parent, Port, Dir)
    after 10000 ->
            io:format("~s failed to report~n", [Dir])
    end.

loop(0) ->
    ok;
loop(N) ->
    receive
        ok ->
            loop(N-1)
    end.
```

I'm sure it could be improved on.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.

**Comment by davidw** [comment]
http://blog.erlware.org/rebar3-features-part-6-_checkouts-2/ - looks like the checkouts mechanism changes things...
