### ISSUE TITLE
generate-appups fails with {badmatch,[]}

### ISSUE THREAD

**Issue by maximvl** [rebar/rebar#282]
I'm trying to run generate-appups, and for some reason rebar cant find previous release .rel file:

```
> ./rebar --version
rebar 2.3.1 R14B04 20140521_211707 git 2.3.1
> ls rel/mysystem_rel/releases/1 
start_clean.boot  start_clean.rel  start_clean.script  sys.config  vm.args  mysystem.boot  mysystem_rel.rel  mysystem_rel.script
> ./rebar -r generate-appups previous_release=rel/mysystem_rel
==> rel (generate-appups)
ERROR: 'generate-appups' failed while processing /home/user/dev/mysystem/rel: {'EXIT',{{badmatch,[]},
         [{rebar_rel_utils,get_rel_file_path,2,[]},
          {rebar_rel_utils,get_rel_release_info,2,[]},
          {rebar_appups,'generate-appups',2,[]},
          {rebar_core,run_modules,4,[]},
          {rebar_core,execute,6,[]},
          {rebar_core,maybe_execute,8,[]},
          {rebar_core,process_dir1,7,[]},
          {rebar_core,process_each,5,[]}]}}
> head -n 5 rel/reltool.config
{sys, [
       {lib_dirs, ["../deps", "../apps"]},
       {erts, [{mod_cond, derived}, {app_file, strip}]},
       {app_file, strip},
       {rel, "mysystem_rel", "2",
```

According to https://github.com/basho/rebar/blob/develop/src/rebar_rel_utils.erl#L108 there is no file `mysystem_rel.rel` in `rel/mysystem_rel/releases/*/`. But it exists.
It would be nice to have a formatted error message about what file and path rebar expected to find.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
