### ISSUE TITLE
Add sugar for `rebar -C rebar.foo.config`

### ISSUE THREAD

**Issue by talentdeficit** [rebar/rebar#283]
i'd like to contribute some changes that provide sugar for using an alternate config file. something like:

```bash
$ rebar dev:compile    # equiv to `rebar -C rebar.dev.config compile`
```
or
```bash
$ rebar compile.ubuntu    # equiv to `rebar -C rebar.ubuntu.config compile`
```

would such a feature (possibly with different syntax, i'm not married to either form) be well received?

**Comment by tuncer** [comment]
@ferd, didn't the rebar3 fork implement this? If so, should we close this?

**Comment by ferd** [comment]
Yep, does it with profiles. Agreed, and closing.
