### ISSUE TITLE
Document template_dir command line option

### ISSUE THREAD

**Issue by benbro** [rebar/rebar#286]
The template_dir command line option is missing from docs
https://github.com/rebar/rebar/wiki/Rebar-commands
https://github.com/rebar/rebar/wiki/Template-support

Thanks

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
