### ISSUE TITLE
Add support for comparison operators in version numbers 

### ISSUE THREAD

**Issue by AeroNotix** [rebar/rebar#297]
Hi,

Re-opening after the great heroku-ing of 2014.

When specifying the version number it would be great to be able to have it work like : `{tag, gt, "0.9.0"}` which would be greater than 0.9.0.

Obviously this only works for a subset of values which people stupidly put there but if we set a precedent to show the usefulness of having version numbers orderable then we'll be happy :)

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
