### ISSUE TITLE
EUnit App Env cleanup is incomplete

### ISSUE THREAD

**Issue by ferd** [rebar/rebar#298]
As reported in https://github.com/rebar/rebar/pull/216 (for which the solution no longer appears to be adequate) 
- We should reuse the test case in https://github.com/rebar/rebar/commit/4935d8124471b4a7423d77461b4058f65cad3b3f while giving credit to @ghost (ideally through pulling that one commit in)
- We should probably add something checking the new [`application:set_env/4`](http://www.erlang.org/doc/apps/kernel/application.html#set_env-4) functionality when in 17.0 or higher

Other notes:
- Basho has reported seeing `application:unload/0` crashing the node from time to time.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
