### ISSUE TITLE
Build open-source projects as part of the CI test suite.

### ISSUE THREAD

**Issue by AeroNotix** [rebar/rebar#301]
I've noticed that rebar master occasionally breaks with various projects in isolation, whilst the unit tests for rebar itself may pass.

A solution:

Build well-known/tricky/whacky/non-standard/odd projects as part of the CI. Known-good commits should be pinned and these should be built by rebar as part of the CI test suite.

What this gives us:

A set of known-good configurations and real-world projects which should hopefully exercise more of rebar's features.

**Comment by tuncer** [comment]
I had to shelve that project, so unless somebody else is working on this, allow me to ask: can/should this be closed?

**Comment by norton** [comment]
No concerns.

**Comment by AeroNotix** [comment]
I don't care any more.
