### ISSUE TITLE
Unify code coverage between QuickCheck and Eunit

### ISSUE THREAD

**Issue by zkessin** [rebar/rebar#312]
When working on a project that has both Eunit and QuickCheck tests rebar can provide coverage info for both types of tests, but not together. so there is no easy way to check if a line is covered by the union of both tests

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
