### ISSUE TITLE
''generate-upgrade'' command does not apply to directory 

### ISSUE THREAD

**Issue by sagungargs** [rebar/rebar#313]
After using the command 

```
$ ./rebar generate-upgrade previous_release=mynode
WARN:  ''generate-upgrade'' command does not apply to directory /Users/NKgarg/Dropbox/Erlang_Self_Tutorials/Testing_Rebar
Command ''generate-upgrade'' not understood or not applicable
```

I am just falling short of one stage before the upgrade '.tar.gz' in 'rel' gets created

Found these links online, but still could not resolve much after consulting and experimenting from them
1) http://lists.basho.com/pipermail/rebar_lists.basho.com/2012-January/001290.html
2) http://www.metabrew.com/article/erlang-rebar-tutorial-generating-releases-upgrades

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
