### ISSUE TITLE
There is no way to pick up protobuf files and compile them other than 'src/*.proto'

### ISSUE THREAD

**Issue by UglyTroLL** [rebar/rebar#324]
Currently, there is no way to pick up and compile the proto files other than 'src/*.proto', while we can do it (specify the 'import path') in the erlang protobuffs compiler by specifying the 'imports_dir' arg (https://github.com/basho/erlang_protobuffs/blob/develop/src/protobuffs_compile.erl#L70), but rebar doesn't pick it up.

I've already created a pull request for this: https://github.com/rebar/rebar/pull/317

**Comment by lrascao** [comment]
closing since PR #317 also has been closed
