### ISSUE TITLE
absolute Paths in RELEASES-File

### ISSUE THREAD

**Issue by pkathmann88** [rebar/rebar#325]
The File rel/$relname/releases/RELEASES currently contains absolute paths to the original release-directory. If I copy the release to another destination and keep the orignal generated directory, the apps from the original /rel/$relname/releases/lib directory are used instead of the libs contained in the release folder. Is this behaviour desired or is this a bug?

If this is a bug, I would be glad to offer my fix for it. If not, I'll just have to stick to my own fork.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
