### ISSUE TITLE
reltool.config release number does not honour that in app.src or .app file

### ISSUE THREAD

**Issue by linearregression** [rebar/rebar#334]
blarblar is compiled successfully and generated a .app file with version number "2.0.0" for vsn.  The vsn is generate by using  rebar able to pick up git tag.
app.src  is {vsn, git}
This number is the same for .app file under ebin under src.
However, when using rebar create-node nodeid=blarblarbalr
reltool.config shows that
rel is "1" which is not the same as 2.0.0
I even tried hard coded vsn number in .app,src but reltool.config still mismatch.

Can you fix that??

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
