### ISSUE TITLE
rebar:run/2 assumes being an escript

### ISSUE THREAD

**Issue by vladdu** [rebar/rebar#343]
Loading the configuration checks for the escript name (see below), but that crashes when not an escript and `init:get_plain_arguments/0` returns `[]`. I would wrap it tn a try...catch, but then what happens when rebar tries to locate resources? What value would make it work with a non-escript install?

I assume that since there is a beginning of an API, the goal is to have it work embedded.

``` erlang
init_config1(BaseConfig) ->
    %% Determine the location of the rebar executable; important for pulling
    %% resources out of the escript
    ScriptName = filename:absname(escript:script_name()),
.........

script_name() ->
    [ScriptName|_] = init:get_plain_arguments(),
    ScriptName.
```

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
