### ISSUE TITLE
Common test no longer working

### ISSUE THREAD

**Issue by cjimison** [rebar/rebar#346]
Hey all,

This is just a question.

I just upgraded to the latest version of rebar and when I run my common tests I get the following error.

Command 'ct' not understood or not applicable

my project struct

./rebar
./rebar.config
./apps/app_1
./apps/app_2

Not really sure what the issue is here and any help would be greatly appreciated.  My expectation is I am doing something wrong or deprecated.

Thanks

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
