### ISSUE TITLE
Parse transform in rebar config doesn't work

### ISSUE THREAD

**Issue by kejv** [rebar/rebar#357]
First, let me present a motivation for having a parse transform in rebar config file. In our company we slowly start adapting to erlang r17 and we have to solve an issue which I guess almost eveybody has to deal with: backwards incompatible change of dict(), set(), etc. types. Approach taken here in rebar project isn't an option for us since we use those types in many modules and also don't want to have that version-conditioned macro in every new module. We think that much more transparent approach is to apply parse transform which just modifies the types according to given version. This means that we want to apply parse transform to every module (even the future ones) and have this stated only in one place: rebar.config (as opposed to having to write parse_transform compile option to every single module). 

So, in order that parse transform works correctly, it has to be compiled befory any "other" modules, i.e. in a way similar to erl_first_files. I have that almost fixed in my fork but I still see couple of problems and I want them solved before I send a pull request:
- Modules from subprojects (dependencies) are compiled before modules from main project. But the subprojects also inherit main project's rebar config which means that parse transform is applied to subprojects before it is actually compiled, which is of course an error. I think that in this situation, though, it makes sense just to ignore any parse transforms for subprojects.
- Second one is tougher. Which modules from main project should be compiled first: parse transform or erl_first_files? I can imagine that both possible orders make sense so I would like to start a discussion on this topic here.

I am using most recent version of rebar as of today (#9583d45).

**Comment by lrascao** [comment]
Closing as both #466 and #477 have been merged
