### ISSUE TITLE
Compile rebar with plugins instead of each project depending on them

### ISSUE THREAD

**Issue by expelledboy** [rebar/rebar#358]
It does not make sense for a project that uses rebar to have a dependency on a rebar plugin. A dependency in my mind is one that is required for the code to function. If I have a plugin that informs Jira of my activity on repo changes I dont see why a project to scrape the web "requires" that functionality to be deployed in order to function.

I propose that plugins are built and deployed as part of the rebar binary.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
