### ISSUE TITLE
Cached dependencies

### ISSUE THREAD

**Issue by expelledboy** [rebar/rebar#359]
We are in the process of migrating to rebar from our custom build scripts. One feature which is difficult to let go (mostly from our IT department) is dependency caching.

We have 5 project. which make use of 30 dependencies, hosted outside of our local network. For each build of these projects we checkout the repositories from scratch, even though the repository can be sourced from local checkouts.

Considering we are a department of 15, and our hourly builds do fresh checkouts, not only do the builds take longer but the network traffic has increased by almost 20 times what it was!

Would it be possible to add this functionality?

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
