### ISSUE TITLE
provide command line settings to get informations about the Erlang installation

### ISSUE THREAD

**Issue by benoitc** [rebar/rebar#364]
It would be useful to have a setting in rebar that would allows to retrieve some information from the erlang installation like the lib dir, version, arch, .... 

Such informations could be use in a Makefile for some custom builds.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
