### ISSUE TITLE
Slow update-deps

### ISSUE THREAD

**Issue by platinumthinker** [rebar/rebar#369]
Rebar slow run 'update-deps' command in large project. I see in debug output - app dependency in few apps repeat evalate..

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
