### ISSUE TITLE
Windows continuous integration

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#374]
It'd be great to make use of http://www.appveyor.com for Windows continuous integration.

If the project admins create a rebar account at appveyor and link to it in the repo settings, I can take a look at adding the needed build+test config.

**Comment by tuncer** [comment]
ping?

**Comment by ferd** [comment]
I checked it, and to sync it with github, it wants to have read access to a bunch of stuff in my accounts and organization. It turns out one of my organizations is my workplace, and I'm not willing to open up github permissions to that.

**Comment by tuncer** [comment]
Is creating a `rebar-win-ci` user an option?

**Comment by ferd** [comment]
I know I personally won't have the required permissions to promote it as a maintainer of the org or whatever.

**Comment by tuncer** [comment]
@lrascao can you look into this?

**Comment by lrascao** [comment]
Sure thing, can't use my user as i have the same issue as @ferd.
So i've created the `rebar-win-ci` github user and configured appveyor to build a fork of rebar, works out of the box pretty well, smooth build. I've got the creds of the user with me, any ideas on the best way to share them?
Tests, not so smooth, most file related tests are failing, i'm not on Windows so it's a bit hard to debug, is any of us on Windows?

**Comment by tuncer** [comment]
> Sure thing, can't use my user as i have the same issue as @ferd.
So i've created the rebar-win-ci github user and configured appveyor to build a fork of rebar, works out of the box pretty well, smooth build. I've got the creds of the user with me, any ideas on the best way to share them?

What permissions does the user require for the repo. Does it need write permissions in rebar/rebar to be linked in the hook?

> Tests, not so smooth, most file related tests are failing, i'm not on Windows so it's a bit hard to debug, is any of us on Windows?

I don't know of any current rebar contributor developing on Windows, but there have been past contributors who primarily used Windows. We could try to contact them.

**Comment by lrascao** [comment]
> What permissions does the user require for the repo. Does it need write permissions in rebar/rebar to be linked in the hook?

Two application require permissions:
* AppVeyor:
  * Read org and team membership
  * Access user email addresses (read-only)
*AppVeyor CI:
  * Full control of repository hooks
  * Read org and team membership
  * Access commit status

**Comment by tuncer** [comment]
What's `Full control of repository hooks`?

**Comment by lrascao** [comment]
I imagine it's access to the webhook REST API (https://developer.github.com/v3/repos/hooks/), rebar has Travis so i'm guessing it's already giving out Write Hook access

**Comment by tuncer** [comment]
If we already have to allow that for Travis, then I suppose we'll have to live with it, even though I don't know why a hook should be allowed to modify a repo's hooks. It sounds reckless.

Also, we can ignore the results of AppVeyor while we work towards fixing the issues in rebar/rebar, circumventing the need for a Windows workstation. Or do you think that's a bad idea?

So, how do we enable it for rebar/rebar?

**Comment by lrascao** [comment]
oops, the comment above is mine, was logged with the rebar-win-ci by mistake

**Comment by tuncer** [comment]
Can you make the config changes, or do we need assistance from @ferd or @jaredmorrow?

**Comment by lrascao** [comment]
we do, an org owner must add `rebar-win-ci` to the Continuous Integration team i've just created with read-only access, hopefully this should do the trick

**Comment by jaredmorrow** [comment]
@lrascao I just sent an invite to @rebar-win-ci and added it to your CI team.

**Comment by tuncer** [comment]
Thanks, @jaredmorrow!

@lrascao I'd say let's add the badge to the README and if possible not enable it for pull request up until all regressions are corrected first.

**Comment by tuncer** [comment]
Thanks, @jaredmorrow!

@lrascao I'd say let's add the badge to the README and if possible not enable it for pull requests until all regressions are corrected first.

**Comment by lrascao** [comment]
Thanks! @jaredmorrow, there should an approval request for appveyor to access the org data through @rebar-win-ci pending in your email

**Comment by lrascao** [comment]
#549 submitted, builds/tests enabled on master only, badge added to README

**Comment by lrascao** [comment]
#549 has been merged, so i guess what's missing now is activating it for pull requests, only the org owner can do so i believe, @jaredmorrow could you take a look please?

**Comment by lrascao** [comment]
ping? is @jaredmorrow the only org owner who could activate Appveyor?

**Comment by tuncer** [comment]
@lrascao, given that the config file has been merged already, can we hook this up at AppVeyor?

**Comment by lrascao** [comment]
I'm afraid that i really don't have time anymore to pursue these kind of improvements to rebar2, i've since made the switch on all my projects to rebar3 (and i think a lot of the community has as well).
However i understand that a lot of projects still need to depend on rebar2 to work on newer OTP versions and i don't see a reason not to give write access to @tuncer for continued support, @ferd would you agree?

**Comment by tuncer** [comment]
I don't have the bandwidth to maintain rebar2. I'm just trying to clean the backlog that's accumulated. Tickets that are open and will not be resolved should be closed. Leaving them open indefinitely isn't a great idea. I closed my obsolete tickets and patches already.

Let's fix the Dialyzer warnings that got introduced and with the Dialyzer integration (#620) merged it won't get new inconsistencies past CI.

**Comment by tuncer** [comment]
Concerning this ticket, I guess we can close it, leaving the appveyor config unused in the repo.

**Comment by ferd** [comment]
@lrascao I do not have access to set new committers or anything like that.
