### ISSUE TITLE
Hook on complete processed project

### ISSUE THREAD

**Issue by platinumthinker** [rebar/rebar#377]
I change my app.src with parse transform when i compile .erl files. Rebar transform app.src to .app. I need hooks on finish compile

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
