### ISSUE TITLE
run common tests in deps

### ISSUE THREAD

**Issue by platinumthinker** [rebar/rebar#379]
Structure my project:
src:
- app.erl
- app.app.src
  deps:
  - lib1:
    - src
    - test
  - lib2:
    - src
    - test

How can i run ct for deps? Unit tests evalate for deps, but ct don't work recursive

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
