### ISSUE TITLE
use "get" instead of "get_local" when determine which protobuf compiler to use

### ISSUE THREAD

**Issue by yizhenfei** [rebar/rebar#383]
Hello all,

When select the protobuf compiler, rebar uses the get_local api:

Key = rebar_config:get_local(Config, proto_compiler, Default),

So, for every subdirs which uses protobufs, there has to be an explict {proto_compiler, gpb} in rebar.config.
I think for most projects, there will only be one proto compiler in use.
Maybe it's better to use "get" instead of "get_local", so that a {proto_compiler, gpb} in the toplevel rebar.config gets to work.

BTW:
The same issue exists for gpb_opts.

**Comment by tuncer** [comment]
What's the status here?

**Comment by ferd** [comment]
Nothing new in a very long while, will close and reopen if needed.
