### ISSUE TITLE
Dependency warning, does not recognize app dir

### ISSUE THREAD

**Issue by Taddic** [rebar/rebar#388]
I get the following warning when trying to pull down dependencies. 
WARN:  Expected /home/tommy/git/ODDA-the-game/lib/yaws to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/tommy/git/ODDA-the-game/lib/jiffy to be an app dir (containing ebin/*.app), but no .app found.

I've searched online extensively, including various blogs and stackoverflow and only found a single reference to the same problem, which was at the following location: https://github.com/basho/riak_ensemble/issues/50
I've tried with yaws, jiffy and riak (the latter just for testing if the issue was there or not).
I don't see anything weird in my rebar.config either. I can paste my rebar.config file structure if needed.

It works fine even with the warning, but it is annoying and I figure it could potentially cause problems in some scenarios.

**Comment by tuncer** [comment]
It's a bug, @ferd can you assign this to me? I'll fix it asap, after verifying my theory.

**Comment by tuncer** [comment]
See #444 for a fix.

**Comment by tuncer** [comment]
Fixed in master (59d1d0c).
