### ISSUE TITLE
No matter what you set src_dirs to, ".app.src" has to be in ./src to compile

### ISSUE THREAD

**Issue by joedevivo** [rebar/rebar#389]
I had assumed that if I gave a `rebar.config` like so:

``` erlang
{erl_opts, [{src_dirs, ["src/main/erlang"]}]}.
```

that rebar would behave as usual if my whole erlang portion of the project lived in `./src/main/erlang`. Rebar was unable to compile anything until I moved my app's .app.src fine directly into `./src`.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
