### ISSUE TITLE
Rebar warnings when referencing project-local dependencies

### ISSUE THREAD

**Issue by tuscland** [rebar/rebar#396]
Hello,

I have a project containing a master `rebar.config` file, an `apps` dir with a few applications we write, and a `deps` containing the shared dependencies.

Our "apps" are also dependent on each other.

Here is a basic file system illustrating our layout: 

```
./rebar.config
./apps/app1/
./apps/app1/rebar.config
./apps/app1/src/
./apps/app1/ebin/
./apps/app2/
./apps/app2/rebar.config
./apps/app2/src/
./apps/app2/ebin/
./deps/[...]
```

We noticed that dependencies were not satisfied in the right order if we did not specified the "local apps" in `rebar.config`, which makes sense. So let's suppose `app2` depends on `app1`, here is `apps/app2/rebar.config`:

```
{deps, [
      app1
    , {lager, "2.0.3", {git, "https://github.com/basho/lager.git", "2.0.3"}}
    , {gproc, "0.3.1", {git, "https://github.com/uwiger/gproc.git", "0.3.1"}}
]}.
{erl_opts, [{parse_transform, lager_transform}]}.
```

Finally for completeness here is our top-level `rebar.config`:

```
{sub_dirs, [
      "rel"
    , "apps/app1"
    , "apps/app2"
]}.
{lib_dirs, ["apps", "deps"]}.
```

Running `rebar compile` from the top-level directory seems to work fine, but rebar outputs annoying warnings like:

```
"WARN:  Expected /Users/xxx/project/services/deps/app1 to be an app dir (containing ebin/*.app), but no .app found.
```

Since `app1` is already in the `sub_dirs` and `lib_dirs`, couldn't rebar just figure the dependency is satisfied?

I am aware that "umbrella" projects like this one should fetch each dependency from an external git repository, but that's just too painful at this stage of the project where our APIs are not mature enough to get their own space in a dedicated repository.

Thank in advance for your help!

Best,
Cam

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
