### ISSUE TITLE
after generate," can't find  run_erl " in windows,  who can save me???

### ISSUE THREAD

**Issue by jiangtiqiang** [rebar/rebar#414]
I use rebar to build a otp application,but when I generate success,  I run rebarapp start ,I got a error :  ..../erts-6.0/bin/run_erl:No such file or directory, can you give some help? thank you...

**Comment by tuncer** [comment]
@jiangtiqiang if you can provide more information, we might be able integrate the changes into the templates. In fact, as you have access to Windows, would you like to submit a patch?

**Comment by tuncer** [comment]
@jiangtiqiang if you can provide more information, we might be able integrate the required changes. Actually, as you have access to Windows, would you like to submit a patch?

**Comment by tuncer** [comment]
@jiangtiqiang, does the problem persist, or can this be closed?

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
