### ISSUE TITLE
Hot-upgraded release doesn't install 'nodetool' file by default.

### ISSUE THREAD

**Issue by seriyps** [rebar/rebar#427]
[runner script](https://github.com/rebar/rebar/blob/3288afa5c1045a5ca1ec53030533645938a45778/priv/templates/simplenode.runner#L138-L147) looks for [nodetool](https://github.com/rebar/rebar/blob/3288afa5c1045a5ca1ec53030533645938a45778/priv/templates/simplenode.nodetool) in paths `erts-${erts-ver}/bin/nodetool` and `releases/${current-release-ver}/nodetool`.

Default [reltool.config](https://github.com/rebar/rebar/blob/3288afa5c1045a5ca1ec53030533645938a45778/priv/templates/simplenode.reltool.config) has instruction `{copy, "files/nodetool", "releases/\{\{rel_vsn\}\}/nodetool"}`, so, on initial release deploy, nodetool will be installed to `releases/${current-release-ver}/nodetool` and successfully found by runner script.

But when upgrade is then generated and applied by

```
rebar generate-appups previous_release=${name}_0.1
rebar generate-upgrade previous_release=${name}_0.1
cp ${name}_0.2.tar.gz ${name}_0.1/releases/
${name}_0.1/bin/${name} upgrade ${name}_0.2
```

directory `${name}_0.1/releases/0.2/` doesn't contain `nodetool` file!

```
$ tree ${name}_0.1/releases/
<name>_0.1/releases/
├── 0.1
│   ├── <name>.boot
│   ├── <name>.rel
│   ├── <name>.script
│   ├── nodetool  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
│   ├── start_clean.boot
│   ├── start_clean.rel
│   ├── start_clean.script
│   ├── sys.config
│   └── vm.args
├── 0.2
│   ├── <name>_0.2.rel
│   ├── <name>.boot -> start.boot
│   ├── relup
│   ├── start.boot
│   ├── start_clean.boot
│   ├── sys.config
│   └── vm.args
├── RELEASES
└── start_erl.data

2 directories, 18 files
```

And because of that `${name}_0.1/bin/${name}` runner can't find `${name}_0.1/releases/0.2/nodetool` and fail:

```
$ ./${name}_0.1/bin/${name} ping
escript: Failed to open file: <...>/<name>/rel/<name>_0.1/erts-6.0/bin/nodetool
$ ./${name}_0.1/bin/${name} eval '2+2'
Node is not running!  # incorrect, because 'ping_node' doesn't work anymore
```

This happens because `rebar generate-upgrade` doesn't include this `nodetool` file in to upgrade tarball:

```
$ tar -zvtf  ${name}_0.2.tar.gz | grep releases
-rw-rw-r-- 501/501         682 2015-01-10 16:12 releases/<name>_0.2.rel
-rw-rw-r-- 501/501       36221 2015-01-10 16:12 releases/0.2/start_clean.boot
-rw-rw-r-- 501/501         333 2015-01-10 16:12 releases/0.2/sys.config
-rw-rw-r-- 501/501          77 2015-01-10 16:12 releases/0.2/relup
-rw-rw-r-- 501/501         682 2015-01-10 16:12 releases/0.2/<name>_0.2.rel
lrwxrwxrwx 501/501           0 2015-01-10 16:12 releases/0.2/<name>.boot -> start.boot
-rw-rw-r-- 501/501         423 2015-01-10 16:12 releases/0.2/vm.args
-rw-rw-r-- 501/501       36034 2015-01-10 16:12 releases/0.2/start.boot
```

This issue can be ad-hock fixed by replacing `{copy, "files/nodetool", "releases/\{\{rel_vsn\}\}/nodetool"}` with `{copy, "files/nodetool", "\{\{erts_vsn\}\}/bin/nodetool"}`, so it will be installed to ERTS directory on initial install, but this doesn't work with slim releases (see https://github.com/rebar/rebar/pull/52 and https://github.com/rebar/rebar/pull/52/files#diff-2627c58bb19ef9c28441cdd05a691f0dL35).

Suggested fix:
Variant 1: include 'nodetool' in generated upgrade `.tar.gz` file.
Variant 2: in `simplenode.reltool.config` template replace `{copy, "files/nodetool", "releases/\{\{rel_vsn\}\}/nodetool"}` with `{copy, "files/nodetool", "bin/nodetool"}` and change runner script to use this location.

**Comment by tuncer** [comment]
Solution (2) sounds like the better idea. @ferd, what do you think?

**Comment by ferd** [comment]
Variant 2 sounds like an easy fix that will be imperfect, but I can't think of breakage that could hit people in production if they do generate their releases to deploy stuff and whatnot. I'd be fine going with it.

**Comment by tuncer** [comment]
Currently nodetool exists in the erts-x.y sub dir, and we already have things like `to_erl`, `${name}` (runner escript), `erl`, `escript`, etc. in `bin/`. That's why (2) sounds like a good idea to me.

Is your concern that each release should use its own version of the (e)scripts for better compatibility?

**Comment by ferd** [comment]
No, it was a lingering feeling I'm ready to let go of. Let's try (2) then.

**Comment by seriyps** [comment]
I think (2) is better too, because `nodetool` is used mostly from runner script `bin/${name}`, so, why not put them together.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
