### ISSUE TITLE
rebar doesn't respect the order of erl_first_files given in the rebar.conf file

### ISSUE THREAD

**Issue by norton** [rebar/rebar#429]
The problem is that the sorted order of AllErlFiles does not match with the order of ErlFirstFilesConf. The order of ErlFirstFilesConf is specified by the user. The order of AllErlFiles determines the order of ErlFirstFiles.

Please review this snippet of code (https://github.com/rebar/rebar/blob/master/src/rebar_erlc_compiler.erl#L309-L313) to check my reasoning.  Git blame seems to point to this change (rebar/rebar@49c2564).

I have a rough idea for the code changes to address this regression.  However, I would like to confirm if there is a specification for the processing order of the erl_first_files given in the rebar.conf file.  My expectation is the files should be compiled in the configuration specified order.

**Comment by nevar** [comment]
Hi.
While fixing problem with "compile non exist file" break "compile order" =(
I will look at this issue.

**Comment by norton** [comment]
Great! Thank you.

**Comment by tuncer** [comment]
Thanks, @nevar.

**Comment by nevar** [comment]
@norton you can try https://github.com/nevar/rebar/tree/erlc_order for fix.
I need add test before do PR.

**Comment by norton** [comment]
Yes, it works fine.  Thank you.

```
$ ./rebar --version
rebar 2.5.1 R15B03 20150116_040132 git 2.5.1-95-g4eef894

$ make
./rebar compile
==> qc (compile)
Compiled src/qc_gen.erl
Compiled src/qc.erl
Compiled src/qc_gen_http.erl
Compiled src/qc_statem.erl
Compiled src/qc_slave.erl
==> pmod_transform (compile)
Compiled src/pmod_pt.erl
==> ubf (compile)
Compiled src/contract_lex.xrl
Compiled src/contract_yecc.yrl
Compiled src/contract_lex.erl
Compiled src/contract_yecc.erl
Compiled src/ubf_utils.erl
Compiled src/contract_parser.erl
Compiled src/ubf_types_builtin.erl
Compiled src/contracts.erl
Compiled src/contract_driver.erl
Compiled src/contract_manager.erl
Compiled src/contract_proto.erl
Compiled src/proc_socket_server.erl
Compiled src/ubf_plugin_handler.erl
Compiled src/ebf.erl
Compiled src/contracts_abnf.erl
Compiled src/contract_manager_tlog.erl
Compiled src/ebf_driver.erl
Compiled src/qc_ubf_impl.erl
Compiled src/proc_utils.erl
Compiled src/qc_ubf.erl
Compiled src/qc_ubf_types.erl
Compiled src/ubf_driver.erl
Compiled src/ubf_plugin_meta_stateful.erl
Compiled src/ubf.erl
Compiled src/ubf_plugin_stateful.erl
Compiled src/ubf_plugin_meta_stateless.erl
Compiled src/ubf_client.erl
Compiled src/ubf_plugin_stateless.erl
Compiled src/ubf_server.erl
```

**Comment by nevar** [comment]
@norton If you have time you can add test and make PR.
I haven't time until next week.

**Comment by norton** [comment]
I'm in the same situation.  If I have time, I will check into the existing unit tests to see how/where it should be added.

**Comment by norton** [comment]
See #445
