### ISSUE TITLE
ERROR: xref failed with exception rebar_abort

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [rebar/rebar#435]
Hi

While executing rebar xref on a project, I get...
ERROR: xref failed while processing ...: rebar_abort
even though the "only" problem seems to be that I'm using a lib (for protocol buffers) where not all of its exports are being used (that function is not generated by our code, but by an external tool).

I looked at the code (rebar_xref.erl) and (as it stands) on line 63 it is instructed to fail for exports_not_used or undefined_function_calls.
Could this be made into a warning, for example, and not a rebar_abort exception? If so, let me know and I might contribute with a source code modification.

Cheers.

**Comment by lrascao** [comment]
Closing since #434 has since been merged
