### ISSUE TITLE
cross compilation, again.

### ISSUE THREAD

**Issue by tonyrog** [rebar/rebar#436]
What about adding REBAR_ARCH (or similar) where you can alter the system architecture.
I have tried something like:

REBAR_ARCH=arm-linux-gnueabi CC=arm-linux-gnueabi-gcc rebar compile

In this case I changed rebar_utils:get_arch to check for arm and return "32". I did also match x86_64, i386, i686 and so on. The fallback is REBAR_ARCH_WORDSIZE. This would also affects rebar_util:wordsize()

I have tried it and it works ok. What about it?

**Comment by tonyrog** [comment]
REBAR_TARGET could be an other name. Then using that to setup all the CC,LD,AR (binutils) program macros would be great. Maybe default CC=${REBAR_TARGET}-gcc when REBAR_TARGET is set.

**Comment by tuncer** [comment]
This seems useful, and I've usually seen an option named `target` when configuring cross compilation. That said, since rebar is not primarily concerned with building C code, the name `REBAR_TARGET` is likely too unspecific. Maybe `REBAR_ARCH_TARGET`? To be clear, this would override the `erlang:system_info(system_architecture)` part of `rebar_utils:get_arch/0`, right?
cc @ferd @liskin

**Comment by tuncer** [comment]
Or is it better to name it `REBAR_SYSTEM_ARCHITECTURE` to follow `erlang:system_info(system_architecture)`? I think `REBAR_ARCH_TARGET` is fine and more similar to other build systems.

**Comment by ferd** [comment]
I frankly barely ever compile C code and never had the need to cross-compile. I'm not the best person to handle this feature or assess its design. I'm ready to listen to the opinions of more experienced people in that area.

**Comment by tonyrog** [comment]
Ok, I will try REBAR_ARCH_TARGET and REBAR_ARCH_WORDSIZE for now. I tend to do (too) much C code with nifs and drivers, interfacing hardware, so I am in a real need of improving this.

**Comment by tuncer** [comment]
@tonyrog so you're going to submit a patch, right?

**Comment by tonyrog** [comment]
Yes :-)
I have updated get_arch / wordsize / default_env and it looks nice. I Successfully cross compile epx (Erlang pixels) for Samsung Gear :-)

**Comment by tuncer** [comment]
Great!

**Comment by joudinet** [comment]
What about using the ERLANG_ARCH and ERLANG_TARGET variables?
Note that there are some arm64 too (AArch64). So assuming arm is always 32-bit is wrong.

**Comment by tonyrog** [comment]
Do what you want with the patch, or ignore it. I am using my own fork.

**Comment by tuncer** [comment]
@tonyrog please see my comment in #451.

**Comment by lrascao** [comment]
Closing since cleaned up version #520 of #451 has since been merged
