### ISSUE TITLE
+K argument in vm.args doesn't  work, Help

### ISSUE THREAD

**Issue by AnakinSong** [rebar/rebar#438]
When I use rebar generate to package , and add "+K true" to vm.args ,start application ,but the argument doesn't work.  When I watch the process in terminal, "+K true " in vm.args become "-K true". Why?

**Comment by tuncer** [comment]
Why do you think it doesn't work? If what you're seeing is the following, then it's normal behavior, and does not mean kernel-poll is disabled:
```
$ erl +Ktrue
$ ps a|grep Ktrue|grep -v grep
[...] bin/beam.smp -Ktrue -- -root [...]
```

**Comment by AnakinSong** [comment]
But when connect vm using remote_console , I see "kernel-poll:false"

**Comment by tuncer** [comment]
What does the VM (same executable) welcome header say if you run `erl +Ktrue` interactively on the same host?

**Comment by AnakinSong** [comment]
kernel-poll:true . system  is ubuntu server 12.04

**Comment by tuncer** [comment]
I've successfully created a demo release with a dummy app and `+K true` in vm.args:
```
[...]
$ rel/demo/bin/demo console
[...]
> erlang:system_info(kernel_poll).
true
```

Can you share `rel/reltool.config` and `rel/files/*` or more information?

**Comment by ferd** [comment]
The information you see with the remote_console is the information of the remote console, not the system you connect to.

It's printed that way because the node boots locally, but spawns its evaluator on the remote node. Not a bug.
