### ISSUE TITLE
.appup.src files copied to ebin

### ISSUE THREAD

**Issue by lrascao** [rebar/rebar#446]
Currently .app.src files are validated and copied to ebin as .app files, this makes sense because tipically .app.src files are under source control but need to be copied to ebin upon build. The same should apply to .appup.src files, rebar generate-appups helps by generating a first draft of the file, however most of the times we require fine tuning of the appup procedure over time so it's helpful to keep the file also under source control. The same approach is already being used for the OTP libraries, most of them have a appup.src file with the upgrade rules.
I already have a feature branch going so if this is deemed useful i'll proceed with a PR

**Comment by tuncer** [comment]
Generally speaking, this sounds like a useful feature to me.

**Comment by ferd** [comment]
Yeah, agreed.

**Comment by lrascao** [comment]
closing, PR's #449 and #461
