### ISSUE TITLE
Problems with pre/post hooks on Windows/cygwin

### ISSUE THREAD

**Issue by bb4242** [rebar/rebar#450]
pre/post hooks do not appear to behave as expected in many cases on Windows/cygwin.  For example, see tomas-abrahamsson/gpb#31.  In that case, there is a pre hook configuration as follows:
```
{pre_hooks,
 [{compile,
   "build/mk_version_hrl"
   "    < include/gpb_version.hrl.in"
   "    > include/gpb_version.hrl "}
 ]}.
```
Trying to compile this project from a cygwin shell results in:
```
$ rebar compile
==> gpb (compile)
'build' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Command [compile] failed!
```
However, attempting to manually run the hook from the shell works fine (the command succeeds and generates the intended gpb_version.hrl file):
```
$ build/mk_version_hrl < include/gpb_version.hrl.in > include/gpb_version.hrl
```

**Comment by tuncer** [comment]
I don't have access to a Windows env, but if you're willing to do some experiments, we could try to come up with stuff to test on Windows.

**Comment by tuncer** [comment]
cc @tomas-abrahamsson

**Comment by bb4242** [comment]
I'm happy to help run some experiments to gather data that would be useful in debugging this. :)

**Comment by tomas-abrahamsson** [comment]
I don't think I've got a windows + cygwin setup either, so I'm just guessing for things to try:

* change `build/mk_version_hrl` to `build\\mk_version_hrl` (ie slash to backslash, since this is the directory separator on windows, plus one more backslash to escape it)
* change `build/mk_version_hrl` to `./build/mk_version_hrl` (ie prepend with `./`  I don't really think this will help -- and if it does, I wouldn't know why -- but it could be worth a try)

**Comment by bb4242** [comment]
Neither of those suggestions worked, but appending `sh` to the command line appears to work:
```
{pre_hooks,
 [{compile,
   "sh build/mk_version_hrl"
   "    < include/gpb_version.hrl.in"
   "    > include/gpb_version.hrl "}
 ]}.
```
I'm not sure why that's necessary (`mk_version_hrl` already starts with `#!/bin/sh`, and invoking it that way from the cygwin prompt works fine), but it works.

Making the above fix allow the compilation to succeed, but it subsequently fails on the post_hooks step:
```
$ rebar compile -v
==> gpb (compile)
INFO:  sh info:
        cwd: "C:/cygwin/home/bbethke/gpb"
        cmd: sh build/mk_version_hrl    < include/gpb_version.hrl.in    > include/gpb_version.hrl
Compiled src/gpb_scan.xrl
Compiled src/gpb_parse.yrl
Compiled src/gpb_scan.erl
Compiled src/gpb_parse.erl
Compiled src/gpb_codegen.erl
Compiled src/gpb.erl
Compiled src/gpb_compile.erl
INFO:  No app_vars_file defined.
INFO:  sh info:
        cwd: "C:/cygwin/home/bbethke/gpb"
        cmd: git describe --always --tags --match '[0-9]*.[0-9]*'
INFO:  sh info:
        cwd: "C:/cygwin/home/bbethke/gpb"
        cmd: sh -e -c 'is_up_to_date () {
    target="$1"
    shift
    test ! -f "$target" && return 1
    for f in "$@"
    do
        test "$f" -nt "$target" && return 1
    done
    return 0
}

is_up_to_date descr_src/gpb_descriptor.erl \
    descr_src/gpb_descriptor.proto || \
    ( echo "Compiling gpb_descriptor.proto..."
    erl +B -noinput -pa ebin \
        -I `pwd`/descr_src -o descr_src \
        -s gpb_compile c `pwd`/descr_src/gpb_descriptor.proto ) || exit $?
is_up_to_date ebin/gpb_descriptor.beam \
     descr_src/gpb_descriptor.erl || \
  ( echo "Compiling gpb_descriptor.erl..."
    erlc -Idescr_src -Iinclude -o `pwd`/ebin +debug_info \
         descr_src/gpb_descriptor.erl ) || exit $?
is_up_to_date ebin/gpb_compile_descr.beam \
    descr_src/gpb_compile_descr.erl \
    descr_src/gpb_descriptor.hrl || \
  ( echo "Compiling gpb_compile_descr.erl..."
    erlc -Idescr_src -Iinclude -o `pwd`/ebin +debug_info \
       descr_src/gpb_compile_descr.erl ) || exit $? \
'
sh: -c: line 1: syntax error: unexpected end of file
ERROR: Command [compile] failed!
```

**Comment by tomas-abrahamsson** [comment]
Ok, good finding. This makes it possible to work around. It would be nice, of course, if rebar would be able to hide away underlying differences such as these, but for the moment, I'm happy working around it.

(And yes, that horrendous blob of shell text had already out-grown a rebar hook long ago. Moving it to a proper script should have been done long ago.)

(And for those wondering what the fuzz is all about: yes, it is a sort-of-makefile, in a shell script. It needs to be built after gpb is built, so a post hook seemed appropriate, but relying on make in a rebar hook seem wrong somehow, and so I ended up with a piece of shell script for it.)

**Comment by tomas-abrahamsson** [comment]
Clarification: from a gpb perspective, I'm ok with closing this issue, but @bb4242 who opened it originally, might perhaps have something in mind.

**Comment by bb4242** [comment]
Thanks to @tomas-abrahamsson, I think we now have a working gpb branch that builds successfully on both cygwin and linux (https://github.com/tomas-abrahamsson/gpb/pull/33).  But there is a subsequent problem once gpb builds on cygwin (please see https://github.com/tomas-abrahamsson/gpb/issues/31#issuecomment-74591605).  Any thoughts on what might be causing that behavior?

**Comment by bb4242** [comment]
On further investigation, it looks like rebar does find gpb, but still thinks it needs to compile with protobuffs.  Doing a `rebar compile -vv` in a project that contains proto messages gives:
```
==> systemmessages (compile)
DEBUG: Matched required ERTS version: 6.3 -> .*
DEBUG: Matched required OTP release: 17 -> .*
DEBUG: Min OTP version unconfigured
DEBUG: is_app_available, looking for App gpb with Path "c:/cygwin/home/bbethke/systemmessages/deps/gpb"
INFO:  Looking for gpb- ; found gpb-3.17.10 at c:/cygwin/home/bbethke/systemmessages/deps/gpb
ERROR: Protobuffs library not present in code path!
ERROR: compile failed while processing C:/cygwin/home/bbethke/systemmessages: rebar_abort
```
The relevant section of rebar.config:
```
%% Use gpb (https://github.com/tomas-abrahamsson/gpb) as the proto compiler
{proto_compiler, gpb}.

%% See gpb_compile.erl (in deps/gpb/src/) for a description of these options
{gpb_opts, [maps, include_as_lib, use_packages, {verify, always}]}.

```

**Comment by tomas-abrahamsson** [comment]
Just came to think of this: in case you're running a rather recent rebar, from the master branch within approx couple weeks back, then chances are you're running with #447 in which options common to both protobuf compilers moved in under a common option key: `{proto_opts, [{compiler, gpb}, ...]}` is the new way to specify compiler, see the _rebar.config.sample_. Maybe this is what is happening?

The discussion around it was that since no released version of rebar has yet had any support also for gpb as protobuf compiler, there was still time to do the change. If this is what happened, then apparently it affected you. Sorry about that.

**Comment by bb4242** [comment]
Ah, that was it!  As it turns out, I was running a slightly newer version of rebar on cygwin as compared to linux, which explains why it built fine on linux but not cygwin.  Thanks for the suggestion - that probably would've taken me a while to track down on my own. ;)  Everything works as expected now, so I'll go ahead and close this.  Thanks again.

**Comment by tomas-abrahamsson** [comment]
Good to hear!

**Comment by tuncer** [comment]
@tomas-abrahamsson wrote:
> It would be nice, of course, if rebar would be able to hide away underlying differences such as these, but for the moment, I'm happy working around it.

Is this a feature request? If so, can you please file a separate ticket outlining the missing or to-be-changed behavior?

**Comment by tomas-abrahamsson** [comment]
> Is this a feature request?

No, at the moment, I do not want to push this forward into a feature request. Maybe some day when I've dug deep enough to understand why it behaves the way it does, I'll revisit it again, but until then, no.
