### ISSUE TITLE
Jenkins compatible

### ISSUE THREAD

**Issue by platinumthinker** [rebar/rebar#455]
Standart jenkins structure projects:
```   
JENKINS/
          -- jobs/
             --- lib1/
                     workspace/
                          .git/
                          src/
                          test/
                          examples/
             --- lib2/
                     workspace/
```

Rebar don't found workspace dir when unit tests run, but unit tests works if rename 
  workspace dir in lib1. I use in test code:
```code:lib_dir(lib1, examples)```
And it's work when name workdirectory equivalent application name

**Comment by platinumthinker** [comment]
This contrary to OTP principlies. I resolved this specific problem on jenkins: settings in job -> adavanced options -> Use custom workspace and set lib1

**Comment by ferd** [comment]
So I assume I can close the issue?

**Comment by platinumthinker** [comment]
yes
