### ISSUE TITLE
Variable expansion in port_env unexpected behavior

### ISSUE THREAD

**Issue by manderson26** [rebar/rebar#457]
If I pass an expression like: "$PWD/deps/local/lib" in the port env string, it expands to "/deps/local/lib", (expanding to the empty string) but "$PWD something else" expands properly to the contents of $PWD, because there is a space following the variable name. There is a workaround via "${PWD}/deps/local/lib" which expands properly, but that took some time for me to figure out. 

The most confusing part of the experience was the fact that the variable didn't fail to expand, it expanded to "" even though it was defined. 

I think it boils down to the regex in rebar_utils:expand_env_variable using \s when it could use \W below:
RegEx = io_lib:format("\\\$(~s(\\s|$)|{~s})", [VarName, VarName]). What's interesting is that the rebar_port_compiler:expand_vars_loop will identify the PWD variable in "$PWD/" because it uses \$\w to detect candidates for substitution. 

Is the current behavior the intended one? I've a fix with some tests if it isn't (manderson26/rebar  ma/improve_variable_expansion)

**Comment by tuncer** [comment]
Thanks, good catch, and please submit a pull request.
