### ISSUE TITLE
Add diameter compilation to "Rebar commands" wiki

### ISSUE THREAD

**Issue by carlosedp** [rebar/rebar#468]
On the Wiki page **Rebar commands**, Diameter dict compilation should be added:

Source|Target|Description
---------|--------|--------------
dia/\*.dia|src/\*.erl <br> include/\*.hrl|Diameter .erl files <br> Diameter .hrl headers

**Comment by tuncer** [comment]
@ferd, can you edit the page?

**Comment by ferd** [comment]
Done.
