### ISSUE TITLE
Beyond template scope variables

### ISSUE THREAD

**Issue by jacktang** [rebar/rebar#476]
Hi
In rebar (create) template command, we can just set template scope variables. But sometime it is not enough, say some gen_xxx code template we need to add author name, email address and etc.  So I propose three level variables here: 1) global level, the template file is placed in ~/.rebar/global.template 2) OTP node level, the variables are defined in rebar.config 3) template level, and they are defined in xxx.template file. And the value of high level variable should overwrite the low one.

BR
-Jack

**Comment by tuncer** [comment]
cc @ferd

**Comment by ferd** [comment]
I do believe that currently, rebar 2.x supports variables in a) the template file itself (see [[1](https://github.com/rebar/rebar/blob/master/src/rebar_templater.erl#L149-L150)]), b) in the command level, c) the global level you wanted ([[2](https://github.com/rebar/rebar/blob/master/src/rebar_templater.erl#L170-L184)]). 

The global level is supported via the `{template_vars, File}` config value, which expects a file of the form:

```erlang
{var1, val1}.
{var2, val2}.
...
```

If I recall correctly, rebar has a mechanism for a global rebar configuration file, so putting the command there would make the values available to all projects.

What could also be interesting to backport is the mechanism used to [populate usernames and addresses from git or hg](https://github.com/rebar/rebar3/blob/master/src/rebar_templater.erl#L134-L168), instead of using such files, but that's possibly outside of scope for this?

**Comment by jacktang** [comment]
Hi Fred

Thanks for the tips, I will check it later.
I am working on the [dev-console template](https://github.com/jacktang/rebar-templates/blob/master/dev_console.sh) which make erlang/otp app development a bit convenience. 
As you know, rebar supports node/app level variables by passing them through command line, But if there are a lot of variables, I think we define them in rebar.config sounds some more reasonable?

BR

**Comment by jacktang** [comment]
I add some modifications and the commit is [here](https://github.com/jacktang/rebar/commit/fcef74df812a9f6c8fb971686560bb2a5ea261b8). If the patch sounds OK, I can send the pull request.

**Comment by ferd** [comment]
No. As I said, this is *already* supported. 
Add in `{template_vars, "template_vars.config"}` to your rebar.config, then `template_vars.config` can contain data such as:

```erlang
{var1, Val1}.
{var2, Val2}.
```
And load them up for you.

There is no need for additional commits. I don't think we'll be adding a fourth way to support variables when you already have one that is equivalent there.

**Comment by ferd** [comment]
To remain consistent with the command line options which point to a file on disk (`rebar template_vars=file.config`), the option in the file should be `{template_vars, "file.config"}`.

We also should make sure that precedence is given to the command-line config, so it can behave as an override to the config file, and also ensure nothing breaks with existing commands.

**Comment by jacktang** [comment]
> the option in the file should be {template_vars, "file.config"}.

Emm, I found the original code would not read "template_vars" option from rebar.config. And I read the rebar_config.erl source code, [get_global/3](https://github.com/rebar/rebar/blob/master/src/rebar_config.erl#L137) function got the value from 'globals' dict while [get/3](https://github.com/rebar/rebar/blob/master/src/rebar_config.erl#L107) or [get_local/3](https://github.com/rebar/rebar/blob/master/src/rebar_config.erl#L115) got the value from 'opts' dict. That why I didn't handle {template_vars, "file.config"} case in rebar.config. If I am wrong, please point them out. 

If it was a bug, I could like to fix it.

**Comment by ferd** [comment]
Yeah I was confused, the original option reads it from the command line (`rebar template_vars=file.config`). What I'm saying is that to be uniform, the stuff we read from `rebar.config` should work the same as the stuff we get from the command line -- both should handle a file name.

**Comment by jacktang** [comment]
Fred, how about extend `template_vars` in rebar.config
```
{template_vars,  [{global,  "/path/to/file"},
                  {TemplateId,  [{VariableKey, VariableVal}] },
                  {"dev_console", [{name_option, "-name test@host.com"}],
                  ... 
               }]
}
```

we can define both global and template scope variables in `template_vars` section. As usual, the template scope variable values overwrite the global ones. Meanwhile, `template_vars` can be passed through command line (`rebar template_vars=file.config`) , if it exists, the global variables overwrite the ones defined in `global`.

Is above proposal OK? please review it, appreciate your time.

BR

**Comment by ferd** [comment]
To be uniform, the stuff we read from rebar.config should work the same as the stuff we get from the command line -- both should handle a file name.

I still stand by that. I think it would simply be confusing and bad design to have the same option in two different places behind entirely differently.

**Comment by jacktang** [comment]
OK, I agreed with you. So how about rename `template_vars` to `gloabl_template_vars` or `template_vars_file` in command line, and leave `template_vars` in rebar.config for template scope variables?

**Comment by ferd** [comment]
What is so inconvenient with a file? I just can't see myself saying yes to this and then other variations. `template_vars` and then having `global_template_vars` or `template_var_files` (which won't happen because we don't break backwards compatibility) all potentially acting on the same variables is *as* confusing if not more confusing than having the same option behave differently in two places.

**Comment by jacktang** [comment]
> What is so inconvenient with a file?

As mentioned before, my template defined some variables in OTP application scope. For example, it is going to generate the script `erl -name {{node_name}} -pa ...`, and you've told me the `file.config` in `rebar template_vars=file.config` is global (all applications share the file) so it was not satisfied. Maybe you can give the name of config option in rebar.config?

BR

**Comment by ferd** [comment]
In rebar.config:

```erlang
{template_vars, "vars.config"}.
```
In vars.config:
```erlang
{node_name, 'a@localhost'}.
```

How is this giving you a different scope than:
```erlang
{template_vars, [{node_name, 'a@localhost'}]}.
```
I think you might be confused by what "global" mean (the same way I initially was). The "global" config value means it comes from the command line rather than the configuration file.

**Comment by jacktang** [comment]
Yes, I misunderstood the "global" variables. I thought the variables, which looked like "author.name", "company.copyright", "license" etc, had nothing to do with template. 

Now I understand your "global" meaning, Is it reasonable to add TemplateId in config file to void the variable name duplicated? And it would look like (vars.config)

```
{TemplateId, [{Name1, Val1}, {Name2, Val2}] }
```

I am very confused that the different scope variables are mixed in one file.

**Comment by ferd** [comment]
I don't think this is supported at all, and we cannot break backwards compatibility, so no, I don't think we can do that.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
