### ISSUE TITLE
rebar ignores test.config

### ISSUE THREAD

**Issue by ostinelli** [rebar/rebar#483]
In `myapp` I use a standard `sys.config` file.
I want to use Common Tests and pass in a custom configuration file, with tests configuration.

When I look at the [source code](https://github.com/rebar/rebar/blob/master/src/rebar_ct.erl#L332) I see that I should name my file `app.config` and place it in the test directory, which I did.

However, when I try to get the config variables with `ct:get_config(myapp)` I get a `bardarg` error, and `myapp` doesn't start since it cannot read its configuration variables from `test.config`.

Can you please tell me how to do this with rebar, or if this is a bug?

**Comment by tuncer** [comment]
It would be great if you can share a demo project demonstrating the issue.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
