### ISSUE TITLE
How to use if/case in template file

### ISSUE THREAD

**Issue by jacktang** [rebar/rebar#488]
Hi,

I found that rebar_templator.erl processes `if` and `case` instructions, could you please give me some examples?

**Comment by tuncer** [comment]
See #138 and #195. We should document this in an example template or at least as part of the help string printed for `rebar help create` (and create-*). @jacktang, would you like to submit a patch for that?

**Comment by jacktang** [comment]
OK, it is my pleasure.

**Comment by tuncer** [comment]
Thanks.

**Comment by jacktang** [comment]
I modified simplemode.template a little to make it as 'if' instruction example. And we should defined `{withtest, true}` in `foo.vars` file, the command line looks like `rebar create template=simplemod template_vars=foo.vars`. In this alternative, I don't know how to improve `rebar help create` info.

The another way, how about the command line `rebar create template=simplemod withtest=true`? Please review it.

**Comment by tuncer** [comment]
Requiring `withtest=true` is a breaking change in the simplemod template, and there's no good reason to. We have no template syntax example in `rebar help create`, so printing a template that showcases all features would work there, but it may not be a perfect fit. Maybe we should take this opportunity to extend `rebar help` and implement `rebar help -g templates`, where `-g GUIDE` prints a guide. That way, we could embed user guides.

@ferd, what do you think?

**Comment by tuncer** [comment]
Also, we should document both `if` and `case`.

**Comment by ferd** [comment]
Yeah, I'd not break anything we have. If you want it backwards compatible, you might want to use `withouttest` or something, and conditionally omit things.

Otherwise, having a template to showcase it is good. Let's not put stuff where it isn't needed just to show it off. Documenting them and having them as an ad-hoc demo are not required to *both* be there if we don't have a good reason to.

**Comment by jacktang** [comment]
> Also, we should document both if and case.

Wiki is the better place to document the template syntax? 
I didn't find the topic in wiki pages so that I read the source code and wrote some examples.

**Comment by tuncer** [comment]
I'd prefer to have more help built-in, but wiki is okay as a quick solution.

**Comment by jacktang** [comment]
I add `case` instruction example [here](https://github.com/jacktang/rebar-templates/blob/master/test.template) . If someone write the wiki page, you may refer to it (now I don't have right to edit the wiki pages).

And let me try to implement the `rebar help -g templates` idea.

**Comment by tuncer** [comment]
> If someone write the wiki page, you may refer to it (now I don't have right to edit the wiki pages).

Unfortunately, r/w access had to be limited to admins and org members due to SPAM and malicious edits. You can clone rebar.wiki.git and file a ticket to merge your commits.

**Comment by ferd** [comment]
Yeah, I'll have to manually merge the wiki edits. People kept vandalizing them.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
