### ISSUE TITLE
Cannot parse OTP Release version string: 17 on windows

### ISSUE THREAD

**Issue by Slavenin** [rebar/rebar#490]
Hi!
On my Windows 7 system function call ```erlang erlang:system_info(otp_release).``` show "17", but regexp on
https://github.com/rebar/rebar/blob/master/src/rebar_require_vsn.erl#L126 not support this format and i can not compile app. This error occurs only if configure ```erlang {require_min_otp_vsn, "R14B03"}```

**Comment by tuncer** [comment]
We've updated [rebar_utils:otp_release/0](https://github.com/rebar/rebar/blob/master/src/rebar_utils.erl#L403-L437), but it looks like we forgot to do the same for rebar_require_vsn.erl. Would you like to submit a patch? If you do, you'd have to update the tests in https://github.com/rebar/rebar/blob/master/test/rebar_require_vsn_tests.erl as well.

**Comment by lrascao** [comment]
see #587

**Comment by lrascao** [comment]
Closing since #587 as since been merged
