### ISSUE TITLE
Gracefully report missing .app.src file

### ISSUE THREAD

**Issue by nlfiedler** [rebar/rebar#497]
Started a new project, created the src directory, a single Erlang module, a simple Makefile, and a simple rebar.config. Tried to build, and got the following.

$ make
rebar compile escriptize
==> getopt (compile)
==> fixperms (compile)
Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,{error,bad_directory}},
                                [{rebar_core,process_commands,2,
                                  [{file,"src/rebar_core.erl"},{line,92}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,752}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,276}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}
make: **\* [compile] Error 1

What was the problem? I was missing the app.src file. Okay, eventually I figured it out, but it would be terrific if rebar could detect and print a helpful message instead of exploding.

Thanks, I love rebar. Keep up the good work.

**Comment by tuncer** [comment]
This crashed quite far along in the process for a dir it assumed to be processible. Can you share a demo project to reproduce the error?

**Comment by tuncer** [comment]
It most likely fails in the `code:set_path/1` call in rebar_utils:expand_code_path/0`, but there shouldn't be non-existent ebin dirs in the list.

**Comment by tuncer** [comment]
Can you try with the `code-path-check` branch in tuncer/rebar.git and post the output?

**Comment by nlfiedler** [comment]
Rather than make a GitHub project or a gist, either of which might disappear some day, I'll just paste the entire thing here, for posterity. It's pretty small anyway, but it might be less convenient for you. In that case, you have my apologies.

$ cat Makefile
.PHONY: all clean compile

all: compile

compile:
	rebar compile escriptize

clean:
	rebar clean

$ cat rebar.config
{require_otp_vsn, "17"}.

{erl_opts, [debug_info, fail_on_warning]}.

{clean_files, [
    "ebin",
    "fixperms"
]}.

{escript_name, "fixperms"}.
{escript_incl_apps, [getopt]}.

{deps, [
    {getopt, ".*", {git, "https://github.com/jcomellas/getopt/", {branch, "master"}}}
]}.

$ cat src/fixperms.erl
%% -*- erlang -*-

-module(fixperms).

-export([main/1]).

main(_) ->
    io:format("Hello world~n").

$ rebar get-deps
$ rebar -r prepare-deps
$ ~/Downloads/tuncer_rebar/rebar compile escriptize
OK rebar/ebin
OK rebar
==> getopt (compile)
==> rebar_bug_497 (compile)
OK rebar/ebin
OK rebar
ERROR: Not a dir: ebin
file info: ebin:
{error,enoent}
Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,{error,bad_directory}},
                                [{rebar_core,process_commands,2,
                                  [{file,"src/rebar_core.erl"},{line,92}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,752}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,276}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}

Indeed, there is no ebin directory, just the three files mentioned above, and the deps directory. As mentioned initially, putting a very basic app.src file in the src directory avoids the exception.

Thanks.

**Comment by nlfiedler** [comment]
I should also point out that the deps are necessary, without it the bug doesn't occur.

**Comment by tuncer** [comment]
Thanks for the detailed information. I don't know when I'll get around to this, so if you want debug the issue, I'm glad to answer any questions you might have.

Also, `prepare-deps` is `get-deps compile`, so you can skip the extra `get-deps`. And `refresh-deps` is `update-deps compile`.

**Comment by tuncer** [comment]
Created a project as described, and tried with R13B03 and 18.0-rc2, but I cannot reproduce the crash.

**Comment by tuncer** [comment]
FYI:

``{erl_opts, [debug_info, fail_on_warning]}.``

should be

``{erl_opts, [warnings_as_errors]}.``

to use the right Werror option and omit what's already enabled by default (debug_info).

`rebar prepare-deps` is already `rebar -r get-deps compile`, so you can simplify the invocation. Finally, in case you didn't know, have a look at `rebar help`, and you'll be see how you can abbreviate commands (compile -> co, prepare-deps -> p-d, etc.).

**Comment by tuncer** [comment]
@nlfiedler, does the problem persist, or can this be closed?

**Comment by nlfiedler** [comment]
If you can't reproduce it, then it must be gone. Feel free to close this.
