### ISSUE TITLE
erlc: include_lib expanded path potentially outdated

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#506]
It's possible that the expanded include_lib path in the digraph can become outdated and refer to an invalid lib_dir if stuff moves around. One solution is to save the original include_lib path for eventual re-expansion. Maybe we can use the edge or vertex label for that. Also, we may want to special case -file() and -include() as well.

**Comment by tuncer** [comment]
I have an experimental WIP branch, which is being tested in #503.

**Comment by kejv** [comment]
See also https://github.com/rebar/rebar/issues/503#issuecomment-109799905
