### ISSUE TITLE
Equivalent way to define dependencies results in conflicts

### ISSUE THREAD

**Issue by yannayl** [rebar/rebar#507]
Defining the same git dependency twice, with different, yet equivalent, definitions cause conflict when updating the dependencies.

How to reproduce:

``` bash
cd $(mktemp -d)
cat << EOF >> rebar.config
{deps, [
  {pkt, ".*",
   {git, "https://github.com/msantos/pkt.git", "master"}}
  , {epcap, ".*",
   {git, "https://github.com/msantos/epcap.git", {branch, "master"}}}
]}.
EOF
rebar g-d u-d
```

will result in:

```
ERROR: Conflicting dependencies for pkt: [{"From: epcap",
                                           {".*",
                                            {git,
                                             "https://github.com/msantos/pkt.git",
                                             {branch,"master"}}}},
                                          {"From: tmp.R4yabf7lJe",
                                           {".*",
                                            {git,
                                             "https://github.com/msantos/pkt.git",
                                             "master"}}}]
```

This is because on the original rebar.config file, pkt is dependency is declared as `"master"` and in epcap dependency, it's declared as `{branch, "master"}`.
Both declarations are equivalent, yet result a conflict.

**Comment by tuncer** [comment]
It should be easy to expand the revision part to {branch, "master"} prior to doing the check.

**Comment by tuncer** [comment]
Want to contribute a patch?

**Comment by ferd** [comment]
For what it's worth, rebar3 already fixes this, along with other dependency handling overhauls too.

**Comment by tuncer** [comment]
Is this a 2.6.0 blocker?

**Comment by tuncer** [comment]
This is just an error message, so it's not a 2.6.0 blocker.

**Comment by tuncer** [comment]
Because the type-less specifier can be a branch or a revision, I don't know if we can precisely unalias it at all. Maybe we should just turn it into a warning message.

**Comment by ferd** [comment]
Rebar3 handles `"master"` specifically like a branch, the rest like a reference (iirc), and always prints a warning if `{ref, Ref}`, `{tag, Tag}`, or `{branch, Tag}` is not being used to represent a dependency.

**Comment by yannayl** [comment]
@tuncer git knows the exact checkout revision, we can propagate the resolution to git.

I think that if you turn it into a warning, it should appear in `get-deps` as well, for consistency and clarity.
I was quite surprised when it happened (after doing only `get-deps` for a while).

**Comment by tuncer** [comment]
@yannayl, can you try my dep-conflict-master branch?

**Comment by tuncer** [comment]
@yannayl, can you git-am https://github.com/rebar/rebar/commit/fa638e6e5d66.patch and add the missing bits like doing the correct check. I can't spend more time on this before the 2.6.0 release.

**Comment by yannayl** [comment]
@tuncer I looked at it some more and realized I can't compare it before executing `git fetch`, which will be executed only after the check. So this is a dead end in the current implementation. (consider "origin/master~1" and "bcb6a4ea45635f0ee96315ead077676ca062f3b5", before fetch they are equivalent, and today they are equivalent, but tomorrow they may be entirely different).

I couldn't find any other git command that would help, but I am no git expert, maybe there is something in the plumbing commands.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
