### ISSUE TITLE
Clean command does nothing for sub_dirs on Mac OS X

### ISSUE THREAD

**Issue by imfranklin** [rebar/rebar#516]
When there are multiple apps living within subdirectories, like so:
```
{sub_dirs, [
    "apps/app1",
    "apps/app2",
    "apps/app3",
    "rel"
]}.
```
A call to `rebar clean` from the top level directory does not remove any files, or anything at all. Changing to the individual app directories and calling from there functions as expected - `rebar -v clean` called from apps/app1 shows the expected "INFO:  sh info: ... cmd: rm -rf ebin/*.beam", yet shows nothing from the top level.

`rebar compile` and `rebar generate` are handling all subdirectories properly.

Running Mac OS X 10.9, having tried last few versions of rebar in combination with Erlang 17 and 16, all experiencing the same issue.

**Comment by lrascao** [comment]
i think #56 is relevant here, in my projects i define a {recursive_cmds, [clean]} tuple in the top-level rebar.config, to prevent cleaning the deps i use skip_deps=true

**Comment by ferd** [comment]
@imfranklin can you confirm @lrascao 's fix works? If so, I misread this and it isn't a bug.

**Comment by imfranklin** [comment]
@ferd it does work.

On my production servers, which are either CentOS or Debian (and running the stable release of rebar at time of deployment), `clean`...well...cleans it all - recursive by default, it seems. Was this recursive cleaning the previous behavior by default? If so, apologies for bug-reporting a config/function change.

**Comment by ferd** [comment]
Yeah it used to be default behaviour, then got changed when a bunch of commands got reworked. We were just not very attentive with versioning back then.
