### ISSUE TITLE
Options to see how erlc is called

### ISSUE THREAD

**Issue by joudinet** [rebar/rebar#517]
Hi,
While debugging a project that uses rebar for its build process, I was in need of seeing which options are given to erlc. However, even with `-vvvvvvvv`, rebar does not report such information. Any idea/plan how to do that?
P.S.: I even try `strace -f -e execve -s 256 -- rebar compile` but, rebar does not exec to call erlc :-\

**Comment by ferd** [comment]
That's because rebar does not call `erlc` but rather only calls the Erlang library function for compiling files: https://github.com/rebar/rebar/blob/b2147de614732c3da33e0fc4c4ad0a28394f43d7/src/rebar_erlc_compiler.erl#L530-L537

**Comment by joudinet** [comment]
Ok, and is there a rebar option to show the content of Opts just before the compilation?
If not, how do you debug compilation issues that may be due to the options given to the compiler?

**Comment by ferd** [comment]
I don't. Usually things just work. You can see the options in a compiled module by calling `Mod:module_info()` on it; the options passed should be specified.

Otherwise, someone would need to patch in `?DEBUG` prints around the arguments.

**Comment by tuncer** [comment]
> Ok, and is there a rebar option to show the content of Opts just before the compilation?

`$ rebar -vv compile`

**Comment by joudinet** [comment]
@ferd : Thanks. `Mod:module_info()` was indeed useful.
As I'm defining both ERL_COMPILER_OPTIONS
@tuncer: Nope, even with `rebar -vvvvvvvv compile`, it does not show the content of erl_opts and/or ERL_COMPILER_OPTIONS. However, I realize I was trying with rebar 2.5.1 and not rebar 2.6.0. I'm going to retry with the last version (as soon as I fix the extra -m64 flag provided to gcc by rebar, even when I compile to a 32-bit machine).

**Comment by joudinet** [comment]
rebar 2.6.0 does show me the information I was looking for with `-vv`, and that was missing in 2.5.1. Sorry for the noise.
