### ISSUE TITLE
rebar generate's bug ? with otp 17

### ISSUE THREAD

**Issue by yuan2006open** [rebar/rebar#519]
bash-3.2# rebar compile generate
==> rel (compile)
==> exemplar (compile)
Compiled src/exemplar_app.erl
Compiled src/exemplar_sup.erl
==> rel (generate)
ERROR: generate failed while processing /Users/bai/exemplar/rel: {'EXIT',{{badmatch,{error,"Module 'ELDAPv3' potentially included by two different applications: eldap and tsung."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,490}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,415}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,299}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,258}]},
          {rebar_core,process_each,5,[{file,"src/rebar_core.erl"},{line,348}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,250}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,90}]}]}}

**Comment by ferd** [comment]
And is the ELDAPv3 module included by two different applications, eldap and tsung? Because if so, that's not really a bug.

**Comment by tsloughter** [comment]
Yea, this is a bug in processone's eldap and tsung applications, not a bug in rebar.

**Comment by yuan2006open** [comment]
Thank you!  tsloughter  is right!
