### ISSUE TITLE
mac rebar_utils:get_arch() error

### ISSUE THREAD

**Issue by 276361270** [rebar/rebar#523]
rebar_utils:get_arch().
*\* exception error: bad argument
     in function  ets:lookup/2
        called as ets:lookup(rmemo,99721141)
     in call from rmemo:call_1/1 (src/rmemo.erl, line 270)
     in call from rebar_utils:get_arch/0 (src/rebar_utils.erl, line 104)

**Comment by ferd** [comment]
@tuncer  ^ this is your stuff now

**Comment by tuncer** [comment]
The arguments look fine, but maybe the table is lost. @276361270, can you try the debug-ets branch in my fork to check that theory?

**Comment by tuncer** [comment]
The arguments look fine, but maybe the table is lost. @276361270, can you try the debug-ets branch in my fork to test the theory?

**Comment by tuncer** [comment]
ping?

**Comment by tuncer** [comment]
@276361270, does the issue persist? Have you tried the debug branch I mentioned?

**Comment by tuncer** [comment]
@ferd, I think this can be closed, since there's been no feedback from the reporter yet. But feel free to keep it open, if you think my today's ping to @276361270 will get a response.

**Comment by ferd** [comment]
I don't think pings on 2 year old issues are likely to yield great results. I'll close this, but I'll also say I don't really have the bandwidth to maintain 2 rebars anymore. I can't remove myself from the admin list, but I wouldn't expect much from me on this version of the tool for the foreseeable future.
