### ISSUE TITLE
appid with '-' creates invalid .app.src

### ISSUE THREAD

**Issue by jbalint** [rebar/rebar#527]
This command:

`$ rebar create-app appid=a-b`

creates a src/a-b.app.src with unquoted atoms "a-b": `{application, a-b,`

attempting to compile results in error:

```
ERROR: Failed to extract name from <...>/src/a-b.app.src: {error,
                           {error,
                             {1,
                             erl_parse,
                              "bad term"}}}
```

thank you.

**Comment by ferd** [comment]
This bug is at least solved in rebar3. The fix, if to be applied to rebar 2.x is to quote all names (or escape dashes, or forbid them).

**Comment by tsloughter** [comment]
@jbalint why are you using this rebar instead of rebar/rebar3!

**Comment by platinumthinker** [comment]
This work in lastest version in erlang 17.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
