### ISSUE TITLE
Why there is no rebar analyze or rebar dialyzer?

### ISSUE THREAD

**Issue by mingchaoyan** [rebar/rebar#529]
I just want to use dialyzer to analyze my code!

version
rebar 2.1.0-pre 17 20150406_143650 git 2.1.0-pre-171-gcd55176

rebar -c

clean                                Clean
compile                              Compile sources

escriptize                           Generate escript archive

create      template= [var=foo,...]  Create skel based on template and vars
create-app  [appid=myapp]            Create simple app skel
create-node [nodeid=mynode]          Create simple node skel
list-templates                       List available templates

doc                                  Generate Erlang program documentation

check-deps                           Display to be fetched dependencies
get-deps                             Fetch dependencies
update-deps                          Update fetched dependencies
delete-deps                          Delete fetched dependencies
list-deps                            List dependencies

generate    [dump_spec=0/1]          Build release with reltool
overlay                              Run reltool overlays only

generate-upgrade  previous_release=path  Build an upgrade package

generate-appups   previous_release=path  Generate appup files

eunit       [suites=foo]             Run eunit tests in foo.erl and
                                     test/foo_tests.erl
            [suites=foo] [tests=bar] Run specific eunit tests [first test name
                                     starting with 'bar' in foo.erl and
                                     test/foo_tests.erl]
            [tests=bar]              For every existing suite, run the first
                                     test whose name starts with bar and, if
                                     no such test exists, run the test whose
                                     name starts with bar in the suite's
                                     _tests module

ct          [suites=] [case=]        Run common_test suites

qc                                   Test QuickCheck properties

xref                                 Run cross reference analysis

help                                 Show the program options
version                              Show version information

**Comment by ferd** [comment]
2.1.0 is old. 2.6.0 is the current version and it contains dialyzer again.
