### ISSUE TITLE
Possibility to redefine dependency?

### ISSUE THREAD

**Issue by Kitton** [rebar/rebar#531]
I'm wondering if it's possible to do it?
Here's an example
I have rebar.config like this

```
{deps, [
  {bson, ".*", {git, "git://github.com/comtihon/bson-erlang.git", {branch, "legacy"}}},
  {boss, ".*", {git, "git://github.com/ChicagoBoss/ChicagoBoss.git", {tag, "v0.8.15"}}}
]}.
```

There's a bson lib in boss->boss_db->mongodb->bson, but I want that mine 

```
{bson, ".*", {git, "git://github.com/comtihon/bson-erlang.git", {branch, "legacy"}}},
```

will be used instead of that one(boss->boss_db->mongodb->bson).
Is it possible?
Because with my config mine isn't used.

**Comment by ferd** [comment]
I believe rebar has no mechanism for this. This need for better control over dependencies is what eventually led to rebar3 being created.

**Comment by tuncer** [comment]
Related: #222

**Comment by tsloughter** [comment]
As @ferd said, this is supported in rebar3 https://github.com/rebar/rebar3, so it is suggested that you migrate to it for this feature if you need it.

**Comment by platinumthinker** [comment]
Yes, this possible - use git@github.com:hyperthunk/rebar_inheritable_deps.git as plugin for rebar

**Comment by wuchuguang** [comment]
support {deps, [{dir, "/home/erlang/xxxPoject"}]} ?

**Comment by wuchuguang** [comment]
can support file_dir?

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
