### ISSUE TITLE
gen_server upgrade error!

### ISSUE THREAD

**Issue by WanliTian** [rebar/rebar#534]
I have a module named test, like this:

    -module(test).
    -behaviour(gen_server).
    -define(SERVER, ?MODULE).
    
    %% ------------------------------------------------------------------
    %% API Function Exports
    %% ------------------------------------------------------------------
    
    -export([start_link/0, get/1, set/2, get/0, set/1]).
    
    %% ------------------------------------------------------------------
    %% gen_server Function Exports
    %% ------------------------------------------------------------------
    
    -export([init/1, handle_call/3, handle_cast/2, handle_info/2,
             terminate/2, code_change/3]).
    
    %% ------------------------------------------------------------------
    %% API Function Definitions
    %% ------------------------------------------------------------------
    
    start_link() ->
        gen_server:start_link(?MODULE, [], []).
    
    get(Pid) ->
        gen_server:call(Pid, get).
    
    get() ->
        gen_server:call(?MODULE, get).
    
    set(Pid, T) ->
        gen_server:call(Pid, {set, T}).
    
    set(T) ->
        gen_server:call(?MODULE, {set, T}).
        
    %% ------------------------------------------------------------------
    %% gen_server Function Definitions
    %% ------------------------------------------------------------------
    
    init(Args) ->
        {ok, "version-1"}.
    
    handle_call(get, _From, State) ->
        {reply, "get version1 state: " ++ State , State}; 
    handle_call({set, T}, _From, State) ->
        {reply, ok, T}; 
    
    handle_call(_Request, _From, State) ->
        {reply, ok, State}.   
    
     handle_cast(_Msg, State) ->
        {noreply, State}.
    
    handle_info(_Info, State) ->
        {noreply, State}.
    
    terminate(_Reason, _State) ->
        ok.
    
    code_change(_OldVersion, State, _Extra) ->
        {ok, State}.
    
Then I want to upgrade it, like this:

    -module(test).
    -behaviour(gen_server).
    -define(SERVER, ?MODULE).
     
    %% ------------------------------------------------------------------
    %% API Function Exports
    %% ------------------------------------------------------------------
    
    -export([start_link/0, get/1, set/2, get/0, set/1]).
    
    %% ------------------------------------------------------------------
    %% gen_server Function Exports
    %% ------------------------------------------------------------------
    
    -export([init/1, handle_call/3, handle_cast/2, handle_info/2,
             terminate/2, code_change/3]).
    
    %% ------------------------------------------------------------------
    %% API Function Definitions
    %% ------------------------------------------------------------------
    
    start_link() ->
        gen_server:start_link(?MODULE, [], []).
    
    get(Pid) ->
         gen_server:call(Pid, get).
    
    get() ->
        gen_server:call(?MODULE, get).
    
    set(Pid, T) ->
        gen_server:call(Pid, {set, T}).
    
     set(T) ->
        gen_server:call(?MODULE, {set, T}).
         
    %% ------------------------------------------------------------------
    %% gen_server Function Definitions
    %% ------------------------------------------------------------------
    
    init(Args) ->
        {ok, "version-2"}.
    
    handle_call(get, _From, State) ->
        {reply, "get version2 state: " ++ State , State}; 
     
    handle_call({set, T}, _From, State) ->
        {reply, ok, T}; 
    
     handle_call(_Request, _From, State) ->
         {reply, ok, State}. 
    
    handle_cast(_Msg, State) ->
        {noreply, State}.
    
    handle_info(_Info, State) ->
        {noreply, State}.
    
    terminate(_Reason, _State) ->
        ok.
    
    code_change(_OldVersion, _State, _Extra) ->
        io:format("code_change.....here~n"),
        {ok, "version 2"}.
    
    
The result is: when i call the method 'get', i get 
    
    get version2 state: version-1

State is not changed!! Why?

**Comment by WanliTian** [comment]
When starting the process with a name, it works well!

**Comment by WanliTian** [comment]
the content of appup file is 

    {"2", [{"1", [{update,test,{advanced,[]},[]}]}], [{"1", []}]}.

Both these two scenes are save!

**Comment by lrascao** [comment]
could you provide some more detail, such as:
how are you generating the relup?
how are you performing the upgrade?

**Comment by WanliTian** [comment]
for version1:

    rebar generate

for upgrade package

    rebar generate
    rebar generate-appups previous_release=hotrep_1
    rebar generate-upgrade previous_release=hotrep_1

**Comment by lrascao** [comment]
and for applying the upgrade?

**Comment by WanliTian** [comment]
I can get normal result when this gen_server is started by supervisor
but, when it's started by 

     {ok, Pid} = test:start_link(),   %% this start_link calling gen_server:start_link without server name

Its result is wrong

**Comment by WanliTian** [comment]
i upgrade my rel by this:

    release_handler:unpack("hotrep_2").
    release_handler:install_release("2").
    release_handler:make_permanent("2").

**Comment by lrascao** [comment]
Looks good, this is most likely related with Erlang's release manager and not rebar itself, any particular reason for not wanting this gen_server to be supervised?

**Comment by WanliTian** [comment]
I will try it right now!
maybe this is caused for  that the process has no name.

**Comment by WanliTian** [comment]
Ok!

If the gen_server is supervised, It works well!!!

If not, the process's code is replaced ,but state cannot be changed! In other word, code_change is not called!

**Comment by lrascao** [comment]
That's really interesting, please do post here any answers you find that explain this behaviour.
Otherwise this issue should probably be closed @tuncer

**Comment by ferd** [comment]
The behaviour is known and documented. The upgrade process goes down the supervision tree to find which processes to upgrade. That's why you need to give a list of module names in your supervisor's child spec, along with whether it's a worker or not, and that `gen_event` gets a `dynamic` value instead of a list.

This is how things have worked in Erlang for years now and there is no bug or unexpected behaviour involved.
