### ISSUE TITLE
-m64 CFLAG set although unavailable

### ISSUE THREAD

**Issue by debalance** [rebar/rebar#536]
Rebar sets the -m64 CFLAG on architectures where it is not available, e.g. Debian's arm64 (aarch64-linux-gnu) or alpha (alpha-linux-gnu).
This causes the build process to fail.

See for example
https://buildd.debian.org/status/package.php?p=erlang-sqlite3
https://bugs.debian.org/795932

Maybe instead of hard-coding it for every possible architecture, rebar could probe the compiler?

**Comment by tuncer** [comment]
Which rebar version? If it's older than 2.6.0, please update first and retry.

**Comment by tuncer** [comment]
In case you have to backport the fix, fetch https://github.com/rebar/rebar/pull/459.patch.

**Comment by tuncer** [comment]
Hmm, the fix may be incomplete.

**Comment by tuncer** [comment]
This was patched partially in #459. A pull request to complete the fix is welcome.

**Comment by tuncer** [comment]
This was patched partially (LDFLAGS) in #459. If you think CXXFLAGS and CFLAGS should also generally avoid this, please submit a patch.

**Comment by tuncer** [comment]
Alternatively, you can extend `default_env/0` for other architectures.

**Comment by tuncer** [comment]
Fix: #538

**Comment by debalance** [comment]
This change has fixed the build failures on Debian.
