### ISSUE TITLE
How to upgrade/downgrade in rebar3?

### ISSUE THREAD

**Issue by reith** [rebar/rebar#542]
I'm trying upgrade release but all `install`, `upgrade` and `downgrade` commands, on generated binary complain:
```
Node app@localhost not responding to pings.

=ERROR REPORT==== 5-Sep-2015::19:47:19 ===
** System running to use fully qualified hostnames **
** Hostname localhost is illegal **
```

I don't know why _running to use fully qualified hostnames_ while I set `-sname` in erl options. Anyway, I got same "Node is not running" after providing fully qualified domain name.

**Comment by BernardNotarianni** [comment]
I had the same issue. I am wondering if [this commit](https://github.com/rebar/rebar3/commit/13e6563be4b94b4d1cdef11e143867310e73c643) is the source of this problem.

**Comment by knusbaum** [comment]
@reith Why did you close this? Was there a workaround?

**Comment by ferd** [comment]
Part of it is that this is a rebar3 question in the rebar 2.x repository.

**Comment by reith** [comment]
Yes, I posted issue in wrong project.  I think main issue is with [relx](https://github.com/erlware/relx/issues/299) and workaround is not using short name :)
