### ISSUE TITLE
`whoami` should not be used in priv/templates/simplenode.runner - use `id -un` instead.

### ISSUE THREAD

**Issue by ccrusius** [rebar/rebar#544]
The `whoami` command, used in the start/stop scripts, has been obsoleted (`man whoami` on my Mac, and some other OSs, states that), and should not be used. The command is not available anymore on SmartOS and Solaris 11. It should be replaced by `id -un`.

For compatibility with older systems, perhaps the script could try `whoami`, and if it fails, try `id -un`.

**Comment by tuncer** [comment]
How about trying `id -un` first and falling back to `whoami` on failure (`$? != 0`)? Like, say, `$(id -un 2>/dev/null || whoami 2>/dev/null || echo USER_DOES_NOT_EXIST)`.

Can't we use the id instead? If so, isn't `id -u` the most portable option? sudo supports `-u #id` and `-u name`.

**Comment by ccrusius** [comment]
All of those work, and I think `id -un` is as portable as `id -u`, since the `-n` option support is required by POSIX.

You bring another problem, though, because `sudo` is not supported in many systems (old Linux ones, or FreeBSD/NetBSD unless explicitly installed), or doesn't work unless being called by `root` (OpenBSD behaves that way). A more portable command is `su`, which is  a POSIX standard, and only accepts login names (thus needing `id -un`).

I can do the `whoami` fallback. Let me know if you want me to "fix" the `sudo` portability problem at the same time.

**Comment by ccrusius** [comment]
Larger fix submitted.

**Comment by tuncer** [comment]
Thanks.
