### ISSUE TITLE
Request to add committers

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#547]
Provided they're willing, I'd like to propose the following candidates for rebar/rebar write permissions based on their contribution history.
- Luis Rascão (@lrascao)
- Tomas Abrahamsson (@tomas-abrahamsson)
- David Kubecka (@kejv)

**Comment by tsloughter** [comment]
+1

**Comment by ferd** [comment]
Yeah, as much as I'd like to be able to put more time in rebar 2.x, I already struggle to find enough time to do work on rebar3.

As long as the overall objective doesn't change (rebar3 is expected to do the lion's share of new feature development, rebar 2.x cannot break compatibility because rebar3 is technically rebar 3.0.0, and so on) I would be happy to get more hands maintaining rebar 2.x.

**Comment by lrascao** [comment]
+1, willing and able

**Comment by tsloughter** [comment]
Pulling in some owners of the rebar org: @Vagabond @jaredmorrow

**Comment by jaredmorrow** [comment]
+1

**Comment by tsloughter** [comment]
@jaredmorrow or @Vagabond can you do the addition? I can't create a new team.

**Comment by jaredmorrow** [comment]
Sorry, just got back from a long meetup last night.  I added an additional team with them being invited.

**Comment by kejv** [comment]
Hi all,

sorry for late reply, I have just came back from vacation.

I am certainly willing to help (and hopefully also able timewise).

Regards,

David


---------- Původní zpráva ----------
Od: Tuncer Ayaz <notifications@github.com>
Komu: rebar/rebar <rebar@noreply.github.com>
Datum: 1. 10. 2015 21:24:55
Předmět: [rebar] Request to add committers (#547)

"

Provided they're willing, I'd like to propose the following candidates for 
rebar/rebar write permissions based on their contribution history.

   * Luis Rascão (@lrascao(https://github.com/lrascao))
   * Tomas Abrahamsson (@tomas-abrahamsson
   (https://github.com/tomas-abrahamsson))
   * David Kubecka (@kejv(https://github.com/kejv))
   

—
Reply to this email directly or view it on GitHub
(https://github.com/rebar/rebar/issues/547). 





"=

**Comment by tuncer** [comment]
@jaredmorrow, ping re: @kejv?

**Comment by tuncer** [comment]
@kejv, if I understand @jaredmorrow correctly, you should be already invited.

**Comment by jaredmorrow** [comment]
Yes, he's indeed been invited.

**Comment by kejv** [comment]
@jaredmorrow  Hmm, pardon me but I can't see the invitation you are talking about, neither in my github account nor in my mail box. Can you please double check that I was reaaly invited, or direct to the place where I can accept the invitation?

**Comment by jaredmorrow** [comment]
@kejv I just doubled checked and updated the invite.  I don't know how to get rid of the invite and do it again, but it sure seems like it is pending.

![screenshot 2015-12-14 10 41 29](https://cloud.githubusercontent.com/assets/718326/11788655/60d6bfc6-a24f-11e5-8ca1-bffabaed0b31.png)

**Comment by tuncer** [comment]
I think it's safe to close this as resolved by now.
