### ISSUE TITLE
warn_deprecated_function option should take a max_version parameter

### ISSUE THREAD

**Issue by Havvy** [rebar/rebar#548]
The `warn_deprecated_function` option should take a `max_version` parameter and not warn for deprecated functions greater than that version. If the max_version given is unknown to the release, warn on all deprecated functions.

This would prevent issues like the `cpg` application v1.5.0 failing to build on Erlang R18.1 because `now` was deprecated.

It would also require that deprecations are tagged with which version they were deprecated in.

**Comment by tuncer** [comment]
Maybe I'm missing something, but aren't you asking for a feature in `compile:file/2` (used by `erlc`) instead?

**Comment by Havvy** [comment]
Yes, I am. Thanks for pointing that out.
