### ISSUE TITLE
Templates cannot cope with whitespace in paths

### ISSUE THREAD

**Issue by evnu** [rebar/rebar#550]
Some scripts in `priv/templates` have problems with paths containing whitespace. For example, `simplenode.runner`:

```
[mmueller@entelios templates]$ pwd
/tmp/rebar whitespace/priv/templates
[mmueller@entelios templates]$ ./simplenode.runner start
cat: /tmp/rebar: No such file or directory
cat: whitespace/priv/releases/start_erl.data: No such file or directory
grep: /tmp/rebar: Is a directory
grep: whitespace/priv/etc/vm.args: No such file or directory
vm.args needs to have either -name or -sname parameter.
```

I identified `simplenode.runner` and `simplenode.nodetool` to show problems like this. Maybe other scripts are affected as well.

**Comment by evnu** [comment]
To find missing quotation of variables in shell scripts, [shellcheck](https://github.com/koalaman/shellcheck) can be used. shellcheck returns a lengthy list for `simplenode.runner`. Example:

    In simplenode.runner line 6:
    if [ `uname -s` = 'SunOS' -a "${POSIX_SHELL}" != "true" ]; then
         ^-- SC2046: Quote this to prevent word splitting.
         ^-- SC2006: Use $(..) instead of deprecated `..`
    In simplenode.runner line 13:
        exec /usr/bin/ksh $0 "$@"
                                       ^-- SC2086: Double quote to prevent globbing and word splitting.
    In simplenode.runner line 19:

     ......snip.....

**Comment by tuncer** [comment]
@evnu, would you like to submit a patch?

**Comment by evnu** [comment]
@tuncer I will give it a try.

Note that OTP itself has problems with whitespace in paths: https://github.com/erlang/otp/pull/849. Thus, patching the issues here will move the problem further upstream.

**Comment by tuncer** [comment]
Thanks.

rebar has to work with all kinds of OTP versions, including those that haven't fixed the issue. Therefore, it's wise to fix what we can in rebar and the shell scripts.

**Comment by evnu** [comment]
The changes to fix this issue will be rather large. I would like to add unit tests to check that this does not break the wanted behaviour. What is the right place to add such tests?

**Comment by evnu** [comment]
Regarding my note on erlang/otp#849: when using the arguments which do not invoke `escript` (such as `simplenode.runner console`), the referenced bug does not apply, as `erl` is called directly.

**Comment by tuncer** [comment]
> What is the right place to add such tests?

`inttest/`.

**Comment by ccrusius** [comment]
Hi - I think I was CCd because shellcheck showed some potential errors in lines that `git blame` to me. As evnu noticed, these problems occur everywhere in the template.

These things are hard to solve in shell scripts. In all my jobs, whenever we have to provide startup scripts, we end up compiling them for all supported platforms from C source, where the problem is manageable with `exec()` and friends. That's probably an even bigger change, I don't know if anybody would have the stomach to tackle it.

**Comment by evnu** [comment]
See https://github.com/rebar/rebar/pull/554 for a test suite to verify that fixes for this bug do not introduce regressions.

**Comment by evnu** [comment]
I pushed my current state to https://github.com/evnu/rebar/tree/fix-whitespace_in_path-errors. Unfortunately, with erlang/otp#849 pending, there is no good way to actually try the changes, as execution will end as soon as Erlang executables are called. Due to this, testing against the testsuite from https://github.com/rebar/rebar/pull/554 can also not work at this point in time.

I'll leave the branch for future use, but I doubt that it will be of much help as long as the Erlang executables cannot cope with whitespace.

**Comment by tuncer** [comment]
But the fix is useful and not breaking anything with older OTP releases, from what I can tell. If that's true, we should merge it. @lrascao?

**Comment by lrascao** [comment]
yep, looks good, i would however suggest squashing the 3 commits into a single one if possible, makes for cleaner history
+1

**Comment by tuncer** [comment]
In this case, the separate commits are fine, as the separation makes sense. For example, fixup commits are needed for easily reviewing changes to the pr, given GitHub's review system, and those should be squashed, but this looks good to me.

**Comment by tuncer** [comment]
The first commit needs to remove the trailing period.

**Comment by tuncer** [comment]
The first commit needs to remove the trailing period in the commit summary.

**Comment by tuncer** [comment]
And Magnus needs to append his name in THANKS.

**Comment by tuncer** [comment]
Similarly, there shouldn't be merge commits that sync with master, but there's nothing like that in the branch.

**Comment by evnu** [comment]
@tuncer do you mean https://github.com/evnu/rebar/commit/8c8095fc79697906e1951eb12fd340abe169db49 with "first commit"?

**Comment by tuncer** [comment]
I was looking at `Use dirname(1) instead of sh string substitution.`(55598565fc3c), which is part of #554. It's what you referenced, but maybe it's the wrong patchset.

**Comment by tuncer** [comment]
Bump?

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
