### ISSUE TITLE
Proto compiler needs an protos_pb.erl src_out_dir option

### ISSUE THREAD

**Issue by dcarastan** [rebar/rebar#553]
protos_pb.erl comes handy when one tries to parse a stack trace. I have prepared https://github.com/rebar/rebar/pull/552 with a possible fix for it.

Thanks,
Doru

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
