### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#561]
If I'm not mistaken the following are stale branches and can be deleted. Can someone take care of it?

```
* adt-random-suite-order
* adt-update-deps-hooks
* revert-413-undo-386-merge
* jem-add-license-prtool
```

Also, it seems like `2.1` can be deleted as well and, if needed, be replaced with a tag.

/cc @ferd @jaredmorrow

**Comment by tuncer** [comment]
ping?

**Comment by tuncer** [comment]
cc @lrascao

**Comment by tuncer** [comment]
ping?

**Comment by lrascao** [comment]
i'm going to try and map these branches to any pending pull requests, see if they still apply

**Comment by lrascao** [comment]
* adt-update-deps-hooks: #277 #159 unmerged
* adt-random-suite-order #223: merged, i've deleted the branch
* revert-413-undo-386-merge: closed, i've deleted the branch
* jem-add-license-prtool: merged, i've deleted the branch

so actually, the only branch that requires some work is adt-update-deps-hooks, i'll look into it

**Comment by tuncer** [comment]
#277 might be risky change, but ever since the previous refactoring of `update-deps`, there's been regression(s). Some stuff got fixed, other things regressed. See #277 for a detailed discussion with pointers.

**Comment by tuncer** [comment]
@lrascao, any thoughts on pursuing the branch for inclusion or closing this?
