### ISSUE TITLE
erl_first_files, parse_transform 

### ISSUE THREAD

**Issue by wuchuguang** [rebar/rebar#563]
rebar.config ->
{erl_first_files, ["module_strengthen.erl"]}.
{erl_opts, [no_debug_info,
            {i, "include"},
            {srcs, ["src"]}
    ]
## }.

src/com_ets.erl
     -compile({parse_transform, module_strengthen}).
     xxxxxx
     xxxxxx
src/module_strengthen.erl

rebar co
  src/com_ets.erl:none: undefined parse transform 'module_strengthen'

**Comment by wuchuguang** [comment]
{erl_first_files, ["/src/module_strengthen.erl"]}.
{erl_first_files, ["src/module_strengthen.erl"]}.
 i try this two way. but not fix it.

**Comment by ferd** [comment]
Can you specify which version of Rebar you are using?

**Comment by wuchuguang** [comment]
rebar 2.6.0 17 20151113_072031 git 2.6.0-16-g3239e74-dirty

**Comment by nevar** [comment]
Did you try without `erl_first_files`?

**Comment by tuncer** [comment]
What's the status here?

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
