### ISSUE TITLE
if project A depend  project B header file

### ISSUE THREAD

**Issue by wuchuguang** [rebar/rebar#564]
like
A
 rebar.config
    {deps_dir, [B parent path]}

  src/a.erl
    -include("b.hrl").

B
  include/b.hrl

In A project , how i include b.hrl

**Comment by wuchuguang** [comment]
src/a.erl
    -include("B/include/b.hrl").
    -include("b.hrl").
    -include_lib("B/include/b.hrl").
    -include_lib("b.hrl").
 all  report : can't find include "b.hrl"

**Comment by ferd** [comment]
That is not how `deps_dir` works. `deps_dir` lets rebar know where to put the dependencies it fetches. Not which paths to go look at.

**Comment by wuchuguang** [comment]
thanks
