### ISSUE TITLE
erl_opts  support multisource dir , multiinclude dir ?

### ISSUE THREAD

**Issue by wuchuguang** [rebar/rebar#565]
db_driver 
     ebin
     include
     src
           db_helper.erl
                 -include("mysql.hrl").
     mysql
          include
              mysql.hrl
          src
     mongodb
          include
          src
    rebar.config->
           {erl_opts, [warn_export_all,
            warn_unused_import,
            {i, "include"},
            {i, "mongodb/include"},
            {i, "mysql/include"},
            {src_dirs, ["src","mysql/src","mongodb/src"]}]}.

rebar co
    src/db_helper.erl:8: can't find include file "mysql.hrl"

**Comment by wuchuguang** [comment]
db_driver

    ebin

    include

    src

    db_helper.erl

    -include("mysql.hrl").

    mysql

        include
            mysql.hrl
        src
    mongodb
        include
        src
    rebar.config->
        {erl_opts, [warn_export_all,
        warn_unused_import,
        {i, "include"},
        {i, "mongodb/include"},
        {i, "mysql/include"},
        {src_dirs, ["src","mysql/src","mongodb/src"]}]}.
    
    rebar co
    src/db_helper.erl:8: can't find include file "mysql.hrl"

**Comment by lrascao** [comment]
Tried your example with rebar 2.6.1 successfully, what version are you using?

**Comment by lrascao** [comment]
@wuchuguang ping?

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
