### ISSUE TITLE
project A deps common,mysql lib, rebar generate 

### ISSUE THREAD

**Issue by wuchuguang** [rebar/rebar#568]
savserver.rel 
{release, {"savserver","2.0"},{erts,"6.3"},
         [{kernel,"3.1"},....]
}.
.... not find mysql common lib include

**Comment by lrascao** [comment]
Could you please elaborate a bit more on the issue? Maybe an example project here on github that exposes the error

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
