### ISSUE TITLE
"rebar ct" ignores "suites", "groups" and "cases" options if there's a ct spec

### ISSUE THREAD

**Issue by MikeBenza** [rebar/rebar#574]
If you have a [test spec](https://github.com/rebar/rebar/blob/b041bd990d1c5db2a4d6f8bed6897528d467c743/src/rebar_ct.erl#L277), then `suites`, `groups`, and `cases` are [ignored](https://github.com/rebar/rebar/blob/b041bd990d1c5db2a4d6f8bed6897528d467c743/src/rebar_ct.erl#L221) on the command line.  There should be some way to ignore the specs.  At a minimum this limitation should be [documented](https://github.com/rebar/rebar/blob/b041bd990d1c5db2a4d6f8bed6897528d467c743/src/rebar_ct.erl#L70).

**Comment by lrascao** [comment]
I guess we have two options here regarding CT:
  - Document that .spec files always override command line options
  - Change rebar so that command line options override .spec files

I personally prefer the first, i'm more used to look for CT related stuff in the .spec and not on Makefiles, what's everybody's thoughts on this?
cc @tuncer @ferd

**Comment by ferd** [comment]
The first would probably prevent breakage given the current status of the project and how stable that kind of stuff has been.

**Comment by tuncer** [comment]
Yes, we shouldn't change the existing behavior. But, you could of course implement something like `ignore_ct_spec=1` (or another name). That's opt-in and should of course also be documented in `rebar help ct`.

**Comment by lrascao** [comment]
I came across an issue with `rebar ct` that might be relevant to this ticket. In rebar.config you can define  a `ct_dir`entry that states the location of your `_SUITE.erl` files, this is where rebar goes to look for them, however when it goes looking for `.spec` files rebar doesn't know use this directory at all, it just recursively searches from the project root. 
This feels like a bug and if fixed could allow @MikeBenza to define separate test specs each with it's own set of suites.

**Comment by lrascao** [comment]
See #588 for a possible fix. @MikeBenza, this allows you to separate test specs each with their own groups and cases, would this work for you?

**Comment by MikeBenza** [comment]
@lrascao I haven't built it and tested it myself, but based on that diff, I strongly believe that will resolve the issue I had.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
