### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by WanliTian** [rebar/rebar#575]
### question one

I have some questions when using `relbin upgrade`.
All my machines have hostnames like `dev1.bggroup1.wm.com`, and this style hostname will no work.
Why rebar has this limitation(the first dot and all chars after that dot will be removed).
### question two

Is there a way to generate vm.args that set `name` like this `app-name@ip`.
I don't want to using hostname, but ip. The reason is that op always change machines' name for management.

**Comment by lrascao** [comment]
@WanliTian @tuncer I'm sorry, but i really have no idea, i've since moved on to rebar3 which has it's own release management tool (`relx`) which is much nicer than reltool, my suggestion is to make the switch to it.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
