### ISSUE TITLE
rebar on a linux with non-smp kernel

### ISSUE THREAD

**Issue by brigadier** [rebar/rebar#576]
I've recently had an issue on a cheap VPS which had kernel built apparently without smp support. rebar (rebar2) just hangs wor a while on such VPS, then fails with the 'cannot create aux thread' error or something like that. `erl`, built for smp kernels, fails with the same error, but it is still possible to start it with the `-smp disabled` command line option. Is there somethink like this for rebar? The only way to run it that i found is to use `ERL_AFLAGS` env.

**Comment by tuncer** [comment]
You can (1) configure the environment to always have `ERL_FLAGS="-smp disable"` (you wrote `disabled`, but it must be `disable`) and (2) use a patched rebar binary, where you override the default `escript_emu_args` by adding `{escript_emu_args, "%%! -pa rebar/rebar/ebin -smp disable"}` in `rebar/rebar.config` before building. Perhaps you also need `+A0`.

**Comment by tuncer** [comment]
The suggestions will work with Erlang older than 20, but going forward the non-SMP emulator has been removed. Therefore, I think this can be closed.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
