### ISSUE TITLE
enuit: cp -r Permission denied

### ISSUE THREAD

**Issue by matwey** [rebar/rebar#579]
Hello, I am facing the following with erlang 17.1 when do `make test`:

```
==> rebar (eunit)
Compiled src/rebar_file_utils.erl
Compiled src/rebar_xref.erl
Compiled src/rebar_upgrade.erl
Compiled test/rebar_compiler_tests.erl
Compiled src/rebar_eunit.erl
Compiled src/rebar.erl
Compiled test/rebar_xref_eunit.erl
Compiled test/rebar_file_utils_tests.erl
Compiled test/rebar_eunit_tests.erl
ERROR: sh(cp -R tmp_file_utils/source\ dir/file\ 1 "tmp_file_utils/dest (dir)")
failed with return code 1 and the following output:
cp: cannot create regular file 'tmp_file_utils/dest (dir)/file 1': Permission denied

ERROR: sh(cp -R tmp_file_utils/source\ dir "tmp_file_utils/dest (dir)")
failed with return code 1 and the following output:
cp: cannot create regular file 'tmp_file_utils/dest (dir)/source dir/file 1': Permission denied

ERROR: Cannot parse eunit version string: 
ERROR: Cannot parse eunit version string: abc
  All 130 tests passed.
```

**Comment by lrascao** [comment]
These are two tests that are actually expected to fail, they are:
cp_r fails to fs permission errors
cp_r fails to fs permission

you can find them in test/rebar_file_utils_tests.erl

**Comment by matwey** [comment]
Is it possible to hide the messages from user?

**Comment by kbrown** [comment]
And what have you done to troubleshoot?  ( I don't want to insult you by suggesting obvious things)

**Comment by kbrown** [comment]
P.S. ignore my last post.  Hadn't read whole thread.

**Comment by lrascao** [comment]
@matwey i don't see any reason for it not to be possible, we'll more than welcome any pull request in that regard

**Comment by lrascao** [comment]
#329

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
