### ISSUE TITLE
Fix config inheritance

### ISSUE THREAD

**Issue by tuncer** [rebar/rebar#58]
Either remove config inheritance support or require keys that should be inherited to be explicitly configured as _allowed to be inherited_.

- https://github.com/basho/rebar/issues/275
- http://lists.basho.com/pipermail/rebar_lists.basho.com/2012-March/001407.html
- http://lists.basho.com/pipermail/rebar_lists.basho.com/2013-January/001923.html

**Comment by tuncer** [comment]
@ferd has a fix for this been implemented in the rebar3 fork? If so, should we close this?

**Comment by ferd** [comment]
Yeah, I believe rebar3 just shouldn't inherit anything anymore without overrides.
