### ISSUE TITLE
Uncaught error in rebar_core

### ISSUE THREAD

**Issue by Leon-SFS** [rebar/rebar#582]
hi
when i run 
"rebar get-deps" in ejabberd root directory "Uncaught error in rebar_core" happens
and this is my rebar version output command : "rebar 2.0.0 R16B01 20131022_120229 No VCS info available"

Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,
                                 {ok,
                                  {config,"/home/lebird/ejabberd",
                                   [{erl_opts,
                                     [nowarn_deprecated_function,
                                      {src_dirs,[asn1,src]}]},
                                    {xref_queries,
                                     [{"(XC - UC) || (XU - X - B  - (\"gen_transport\":_/_) - (\"eprof\":_/_) - (\".*mysql.*\":_/_) - (\".*pgsql.*\":_/_) - (\"epam\":_/_) - (\"riak.*\":_/_) - (\"lhttpc\":_/_) - (\"odbc\":_/_) - (\"sqlite3\":_/_) - (\"eredis\":_/_))",
                                       []}]},
                                    {ct_extra_params,
                                     "-ct_hooks cth_surefire -include /home/lebird/ejabberd/tools"},
                                    {post_hooks,
                                     [{'get-deps',
                                       "sh -c 'cd deps/p1_tls && CFLAGS=\"\" CPPFLAGS=\"\" LDFLAGS=\"\" ./configure '"},
                                      {'get-deps',
                                       "sh -c 'cd deps/p1_stringprep && CFLAGS=\"\" CPPFLAGS=\"\" LDFLAGS=\"\" ./configure '"},
                                      {'get-deps',
                                       "sh -c 'cd deps/p1_yaml && CFLAGS=\"\" CPPFLAGS=\"\" LDFLAGS=\"\" ./configure '"},
                                      {'get-deps',
                                       "sh -c 'cd deps/esip && CFLAGS=\"\" CPPFLAGS=\"\" LDFLAGS=\"\" ./configure '"},
                                      {'get-deps',
                                       "sh -c 'cd deps/p1_xml && CFLAGS=\"\" CPPFLAGS=\"\" LDFLAGS=\"\" ./configure '"},
                                      {'get-deps',
                                       "sh -c 'cd deps/p1_zlib && CFLAGS=\"\" CPPFLAGS=\"\" LDFLAGS=\"\" ./configure '"},
                                      {'get-deps',
                                       "sh -c 'cd deps/p1_iconv && CFLAGS=\"\" CPPFLAGS=\"\" LDFLAGS=\"\" ./configure '"}]},
                                    {deps,
                                     [{lager,".*",
                                       {git,"https://github.com/basho/lager",
                                        {tag,"3.0.2"}}},
                                      {p1_utils,".*",
                                       {git,
                                        "https://github.com/processone/p1_utils",
                                        {tag,"1.0.3"}}},
                                      {cache_tab,".*",
                                       {git,
                                        "https://github.com/processone/cache_tab",
                                        {tag,"1.0.2"}}},
                                      {p1_tls,".*",
                                       {git,
                                        "https://github.com/processone/tls",
                                        {tag,"1.0.0"}}},
                                      {p1_stringprep,".*",
                                       {git,
                                        "https://github.com/processone/stringprep",
                                        {tag,"1.0.1"}}},
                                      {p1_xml,".*",
                                       {git,
                                        "https://github.com/processone/xml",
                                        {tag,"1.1.2"}}},
                                      {p1_stun,".*",
                                       {git,
                                        "https://github.com/processone/stun",
                                        {tag,"0.9.1"}}},
                                      {esip,".*",
                                       {git,
                                        "https://github.com/processone/p1_sip",
                                        "1.0.1"}},
                                      {p1_yaml,".*",
                                       {git,
                                        "https://github.com/processone/p1_yaml",
                                        {tag,"1.0.1"}}},
                                      {jiffy,".*",
                                       {git,
                                        "https://github.com/davisp/jiffy",
                                        {tag,"0.14.5"}}},
                                      {oauth2,".*",
                                       {git,
                                        "https://github.com/kivra/oauth2",
                                        "8d129fbf8866930b4ffa6dd84e65bd2b32b9acb8"}},
                                      {xmlrpc,".*",
                                       {git,
                                        "https://github.com/rds13/xmlrpc",
                                        {tag,"1.15"}}},
                                      {p1_zlib,".*",
                                       {git,
                                        "https://github.com/processone/zlib",
                                        {tag,"1.0.0"}}},
                                      {p1_iconv,".*",
                                       {git,
                                        "https://github.com/processone/eiconv",
                                        {tag,"0.9.0"}}}]},
                                    {deps_erl_opts,[]},
                                    {plugins,[deps_erl_opts]},
                                    {lib_dirs,[]},
                                    {sub_dirs,["rel"]},
                                    {keep_build_info,true},
                                    {xref_warnings,false},
                                    {xref_checks,[deprecated_function_calls]},
                                    {eunit_compile_opts,[{i,"tools"}]},
                                    {port_env,[{"CFLAGS","-g -O2 -Wall"}]},
                                    {port_specs,
                                     [{"priv/lib/jid.so",["c_src/jid.c"]}]},
                                    local],
                                   {dict,0,16,16,8,80,48,
                                    {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                     [],[],[]},
                                    {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]}}}},
                                  []}},
                                [{rebar_core,acc_modules,5,
                                  [{file,"src/rebar_core.erl"},{line,469}]},
                                 {rebar_core,process_dir0,6,
                                  [{file,"src/rebar_core.erl"},{line,193}]},
                                 {rebar_core,process_dir,4,
                                  [{file,"src/rebar_core.erl"},{line,130}]},
                                 {rebar_core,process_commands,2,
                                  [{file,"src/rebar_core.erl"},{line,83}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,53}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,752}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,276}]},
                                 {init,start_it,1,[]}]}}

whats the problem???

**Comment by lrascao** [comment]
Could you try the latest rebar version? I've had no problem using 2.6.1

**Comment by lrascao** [comment]
@Leon-SFS ping?

**Comment by Leon-SFS** [comment]
@lrascao sorry for late, i update rebar and its fix, i forgot to come back and say it.
tnx for help
