### ISSUE TITLE
error running rebar generate on OSX

### ISSUE THREAD

**Issue by msilvestre** [rebar/rebar#583]
On OSX I'm having an error when running rebar generate.
Searching the internet I didn't find any clue on how to solve it. The erlang I have is the 17.5.

Any clue?

Thanks.

```
$rebar generate
==> rel (generate)
ERROR: generate failed while processing /Users/miguel.silvestre/IdeaProjects/miniclip_server/rel: {'EXIT',{{badmatch,{error,"miniclip_server: Application version clash. Multiple directories contain version \"0.1\"."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,493}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,418}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,302}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,261}]},
          {rebar_core,process_each,5,[{file,"src/rebar_core.erl"},{line,351}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,253}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,93}]}]}}

```

**Comment by ferd** [comment]
"{error,"miniclip_server: Application version clash. Multiple directories contain version \"0.1\"." is being returned. I figure this means you have multiple directories with the application 'miniclip_server' in them, and they all have the same version, which confuses reltool.

**Comment by msilvestre** [comment]
I don't understand the directories problem. I've done everything as on the tutorials..

I've just pushed it to github: 

https://github.com/msilvestre/miniclip_server.git

**Comment by posilva** [comment]
I have tried your repo and I was able to run rebar generate after these steps:

1. Removed rel and files
2. Run rebar create-node nodeid=miniclip_server
3. Edited reltool.config and added "../.." and "../deps" to the lib_dirs entry
4. Run rebar generate and voilá

**Comment by msilvestre** [comment]
Recreating that steps it didn't work for me. :(

Anyone else?

**Comment by msilvestre** [comment]
moved to rebar3..
If anyone has the same issue, try rebar3:
http://www.rebar3.org/
