### ISSUE TITLE
use rebar to generate release. when start app, i got this error: {"init terminating in do_boot",{'cannot load',elf_format,get_files}}

### ISSUE THREAD

**Issue by WanliTian** [rebar/rebar#584]
how to resolve it.

**Comment by lrascao** [comment]
From the `elf_format` error, i would say you are trying to run platform incompatible binaries, are you running the release in the same machine where you compiled it?

**Comment by WanliTian** [comment]
yes, i create and run the release in the same machine.
finally i remove hipe from my machine with `{app, hipe, [{incl_cond, exclude}]}`, then all work well.
