### ISSUE TITLE
rebar_file_utils:cp_r/2 should follow symlinks

### ISSUE THREAD

**Issue by mduller** [rebar/rebar#597]
rebar_file_utils:cp_r/2 is used by rebar_erlc_compiler:test_compile/3 to copy source files to a separate eunit directory, from which they are compiled and cover is run. Currently, cp_r/2 is implemented on Unix-like systems using the shell's cp -R command. This way, symlinks in the source directories are copied as they are (as symlinks) to the eunit directory. For relative symlinks, this can break the symlink. E.g.:

```
src
 + mylink.erl -> some/sub/dir/actualfile.erl
 + some
    + sub
       + dir
          + actualfile.erl
```

will be copied to

```
eunit
 + mylink.erl -> some/sub/dir/actualfile.erl
 + actualfile.erl
```

When compiling from the eunit directory, mylink.erl will not be valid.

rebar_erlc_compiler:test_compile/3 is the only client of rebar_file_utils:cp_r/2. If it's purpose is to create a flat copy of all source files required, I propose it should dereference symlinks instead. I.e., add "L" to the arguments of shell's cp command.

Background: The above is a simplified example. We use subdirectories, symlinks, and includes to create two implementations of the same module from a single source file. The two implementations differ in the byte-order used in binary parsing. We have modified rebar to include "L" in the arguments to cp and it successfully copies the contents of the files the symlinks point to as regular files to the eunit directory.

Related note:

If there is a symlink in the eunit directory (copied by a previous run of rebar), the cleanup in rebar_erlc_compiler:test_compile/3 fails to remove it before copying over the new set of files because cleanup only removes regular files. So while symlinks can work for compilation in the eunit directory (because they point to an absolute path or because their relative target happens to work inside the eunit directory as well), running rebar subsequently will cause an error because cp by default does not overwrite symlinks on most platforms.

**Comment by lrascao** [comment]
Looks good, would you like to submit a PR with the proposed fix and a simple `inttest/` to prevent future regressions?

**Comment by mduller** [comment]
Thanks. I'll submit a PR with test later this week.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
