### ISSUE TITLE
beam/beam_load.c(1317): Error loading module rebar:

### ISSUE THREAD

**Issue by oladipo** [rebar/rebar#601]
After downloading the prebuilt binaries.

I tried to run rebar but got the following error:

oladipo@ubuntu:~/rebar_new$ ./rebar

=ERROR REPORT==== 18-Mar-2016::16:41:42 ===
beam/beam_load.c(1317): Error loading module rebar:
  use of opcode 153; this emulator supports only up to 149

=ERROR REPORT==== 18-Mar-2016::16:41:43 ===
Loading of /home/oladipo/rebar_new/rebar/rebar/ebin/rebar.beam failed: badfile
escript: exception error: undefined function rebar:main/1
  in function  escript:run/2
  in call from escript:start/1
  in call from init:start_it/1
  in call from init:start_em/1

**Comment by lrascao** [comment]
can you post the output from `erl` please?

**Comment by oladipo** [comment]
oladipo@ubuntu:~/otp_src_18.3$ erl
Erlang R13B03 (erts-5.7.4) [source] [rq:1] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V5.7.4  (abort with ^G)
1>

**Comment by lrascao** [comment]
I see that you're in a OTP18 src folder, was that the one you were trying to run?
You have R13 in the path, unfortunately rebar is only supported for R14 onwards

**Comment by tuncer** [comment]
rebar2 runs on anything >= R13B03.

What OTP version did you use when building the rebar binary? It looks like the beam files were built with a newer OTP and make use of opcodes unsupported by R13B03. You should be fine to run it on R13B03 if it was built with R14* and it will definitely work if built with R13B03. In essence, what you compile with R13B03 will work on anything >=R13 but what you compile with a newer OTP version may not run on an older OTP.

**Comment by oladipo** [comment]
Finally installed erlang OTP 18.3 and rebar on a different machine. I guess the previous machine had some configuration issues. Will sort that out later. Thanks everyone
