### ISSUE TITLE
Rebar installation issue

### ISSUE THREAD

**Issue by bedekarsarvesh** [rebar/rebar#604]
Installed rebar , got the rebar file with extension .file .. Tried connecting it to Intellij Idea erlang version , the rebar version shows NA . Any help appreciated
![image](https://cloud.githubusercontent.com/assets/16263319/15777271/8d9b4016-29ab-11e6-92a1-8acae541482e.png)

**Comment by tuncer** [comment]
@bedekarsarvesh, did you resolve this? Judging by the screenshot, you didn't specify the path to the batch file but the escript archive which won't run in the standard Windows userspace that IntelliJ runs in.

**Comment by tuncer** [comment]
There's been little activity here and it's not clear that rebar is at fault, so I'd say it's okay to close.

@bedekarsarvesh, please try rebar3 or reopen if it's a pressing issue you haven't been able to resolve.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
