### ISSUE TITLE
New rebar release?

### ISSUE THREAD

**Issue by fhunleth** [rebar/rebar#607]
Would it be possible to generate a new rebar release? E.g. 2.6.2 or similar so that the accumulated fixes in `master` can be published? If the latest isn't ready for release, including up to e1f7e6a51f5781c626f8d793337215dd70aa7859 is what I need. The particular bug that was fixed by that commit has started coming up more frequently, and it would be really helpful if it could be rolled into an official release.

**Comment by lrascao** [comment]
cc @tsloughter @ferd @tuncer

**Comment by ferd** [comment]
@lrascao if master is ready to tag and release, we can go for it.

**Comment by tuncer** [comment]
+1

**Comment by ferd** [comment]
Released, compiled on R15B03, and updated the wiki link.

**Comment by fhunleth** [comment]
Thanks!!
