### ISSUE TITLE
rebar bootstrap fails on first run

### ISSUE THREAD

**Issue by firephreek** [rebar/rebar#613]
Clean download/clone of latest from master, Win 10, x64, etc...

Running bootstrap.bat results in the following message:

> escript: exception error: no match of right hand side value "Could Not Find <root>\\rebar\\ebin\\rebar.beam\r\n"

Traced the issue to the case statement on line 23 and the false -> rm("ebin/rebar.beam") statement.  On a clean download, the ebin folder only has a single file: 'rebar.app', so the rm function fails to resolve.

Solution: Explicit check for file existence.  I'm new to Erlang so there's probably a more elegant solution, but in the meantime, this works:

`case lists:member("force=1", Args) of
        true ->
            rm("ebin/*.beam");
        false ->
            case filelib:is_file("ebin/rebar.beam") of
               true -> rm("ebin/rebar.beam");
               false -> io:fwrite("No beam files found.~n")
            end
    end,`

If the first case false fires, we check for the file to exist before we try to remove it. Print a nice message, and everything seems to work fine after that.

**Comment by lrascao** [comment]
Hi, thanks for the find, don't have access to a windows system right now, would a `del /f /q` also do the trick?

**Comment by firephreek** [comment]
No, del doesn't help here unfortunately since the directory is already empty. 

The installation instructions right now are simply 'clone, cd rebar, run botstrap'.  At that point, the escript does a check for a `force=1` arg (line 23) and does `rm("ebin/*.beam")` and `rm("ebin/rebar.beam")`if it doesn't.  Since the ebin folder is already empty on a clean checkout, and the user hasn't provided force=1, the second rm command fails because the file doesn't exist.

Current workarounds that I see:
 - touch/create ebin/rebar.beam, run bootstrap.bat.  Requires instruction.
 - do rm("ebin/*.beam") all the time.  Probably a risk to compile process.
 - explicit file exists check. PR does this.

**Comment by lrascao** [comment]
thanks, #613  has been merged

**Comment by benseshi** [comment]
ben@kali:~/Downloads/rebar-master$ ./bootstrap
./bootstrap:40: Warning: string:strip/3: deprecated; use string:trim/3 i
./bootstrap:149: Warning: string:strip/3: deprecated; use string:trim/3 
./bootstrap:150: Warning: string:strip/3: deprecated; use string:trim/3 
Recompile: src/rebar
src/rebar.erl:529: Warning: string:tokens/2: deprecated; use string:lexe
stead
src/rebar.erl:596: Warning: string:join/2: deprecated; use lists:join/2 
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,
                                  [{file,"src/rebar.erl"},{line,209}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {erl_eval,do_apply,6,
                                  [{file,"erl_eval.erl"},{line,670}]},
                                 {escript,eval_exprs,5,
                                  [{file,"escript.erl"},{line,873}]},
                                 {erl_eval,local_func,6,
                                  [{file,"erl_eval.erl"},{line,557}]},
                                 {escript,interpret,4,
                                  [{file,"escript.erl"},{line,789}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]}]}}
please can anyone help to solve this its make me freak out

**Comment by tuncer** [comment]
@benseshi, that's an unrelated error and means your Erlang/OTP installation is missing a functioning cryto app (which requires linking OpenSSL). If you built from source, you may have forgotten to install OpenSSL development files first. Otherwise, if you installed from a binary repo that has split Erlang packages, you may need to install the crypto package too.

**Comment by benseshi** [comment]
How to install them bro

**Comment by benseshi** [comment]
../test/recipes/40-test_rehash.t                 (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=137, Tests=1130, 421 wallclock secs (13.43 usr  1.98 sys + 318.87 cusr 142.84 csys = 477.12 CPU)
Result: FAIL
Makefile:167: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/ben/openssl'
Makefile:165: recipe for target 'tests' failed
make: *** [tests] Error 2
when im trying to install openssl im gettin this error
can anyone help me please

**Comment by tuncer** [comment]
OpenSSL should be already available if you installed any kind of desktop environment in your operating system. And the OpenSSL development packages, if packaged separately as on distros like Fedora or Debian/Ubuntu, are an extra install (libssl-dev, openssl-devel). Please use that if you want to build Erlang from source.

However, given the errors you ran into, may I suggest installing Erlang binary packages for your operating system? They can be found in most Linux distros and also BSD package repos.

If you have further questions, please consider subscribing to and asking on the erlang-questions@erlang.org mailing list or the IRC channel.  Using rebar assumes you already have a working Erlang installation, so this unrelated ticket isn't really the right place to troubleshoot that. Don't forget to include your operating system info if you ask.
