### ISSUE TITLE
Possibile C compiler regression 2.6.2->2.6.3

### ISSUE THREAD

**Issue by olgeni** [rebar/rebar#622]
Hi,

I upgraded from 2.6.2 to 2.6.3 and tried to build https://github.com/processone/fast_xml, which worked fine with 2.6.2.

With 2.6.3 I get this error:

    ERROR: compile failed while processing /usr/local/poudriere/ports/erlang/textproc/erlang-fast_xml/work/fast_xml-1.1.15: {'EXIT',
        {function_clause,
            [{lists,reverse,
                 [["c_src/fxml_stream.o"|
                   {["c_src/fxml.o"],
                    ["{ \"file\"      : \"c_src/fxml.c\"\n, \"directory\" : \"/usr/local/poudriere/ports/erlang/textproc/erlang-fast_xml/work/fast_xml-1.1.15\"\n, \"command\"   : \"cc -c -O2 -pipe -I/usr/local/include -fstack-protector -fno-strict-aliasing -g -O2 -Wall -g -Wall -fPIC -MMD -I\\\"/usr/local/lib/erlang/lib/erl_interface-3.9/include\\\" -I\\\"/usr/local/lib/erlang/erts-8.0.3/include\\\" c_src/fxml.c -o c_src/fxml.o\"\n}~n"]}]],
                 [{file,"lists.erl"},{line,147}]},
             {rebar_port_compiler,compile_each,5,
                 [{file,"src/rebar_port_compiler.erl"},{line,240}]},
             {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
             {rebar_port_compiler,compile_sources,3,
                 [{file,"src/rebar_port_compiler.erl"},{line,220}]},
             {rebar_port_compiler,compile,2,
                 [{file,"src/rebar_port_compiler.erl"},{line,58}]},
             {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,493}]},
             {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,418}]},
             {rebar_core,maybe_execute,8,
                 [{file,"src/rebar_core.erl"},{line,302}]}]}}
    *** Error code 1

I downgraded back to 2.6.2 and indeed it seems that 2.6.3 is having issues with this build.

The list construction here seems odd: `["c_src/fxml_stream.o" | {["c_src/fxml.o"], ...`

**Comment by lrascao** [comment]
Thanks, could you please try again with the fix in PR #619 and check if that fixes your issue?

**Comment by olgeni** [comment]
Checked - seems to be working fine!

**Comment by lrascao** [comment]
cool, thanks!

**Comment by lrascao** [comment]
PR #619 merged to master, will cut 2.6.4 still today hopefully

**Comment by lrascao** [comment]
2.6.4 is out
