### ISSUE TITLE
bootstrap.BAT Windows-10 Issue

### ISSUE THREAD

**Issue by CO600-ol38** [rebar/rebar#626]
I am a Windows-user and am trying to integrate Rebar-3 for IntelliJ Erlang.

I put the Rebar-3 directory in '//erl8.1/lib/'.
Then, when I try to compile 'bootstrap.BAT' it ALWAYS SAYS 'escript.exe' un-recognized.

Is this a problem with the Erlang-shell, Rebar or Windows??

**Comment by tuncer** [comment]
@CO600-ol38, is Erlang in `%PATH%`? Can you execute `escript`?

@lrascao, assuming this is a Windows issue, can Appveyor test on Windows 10?

**Comment by lrascao** [comment]
shouldn't this issue be in the rebar3 project instead?
not sure on Appveyor, can't find anything in their site referring Windows 10 support

**Comment by sepasti** [comment]
Hi I have same problem in windows 10, how to fix it?
thanks in advance

**Comment by lrascao** [comment]
@sepasti is your problem also in rebar3?

**Comment by sepasti** [comment]
Yes, I have this problem also in rebar 3.

**Comment by lrascao** [comment]
but is your problem specifically in rebar2 or rebar3?

**Comment by sepasti** [comment]
both of them not woking, maybe in window 10's problem, when I ran bootstrap.bat, it returns this error:
C:\Program Files\erl8.2\rebar3-master>bootstrap.bat
'escript.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lrascao** [comment]
seems like your erlang is not properly installed, `escript` should be in your PATH

**Comment by sepasti** [comment]
I removed OTP 19.2 and install OTP 18.3, but not working:

C:\Program Files\erl7.3\lib\rebar3-master>bootstrap.bat
'escript.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lrascao** [comment]
before running the bootstrap.bat you should be able to run `escript` directly from the path

**Comment by sepasti** [comment]
you're right, that works. thanks for your kind response

**Comment by lrascao** [comment]
👍
