### ISSUE TITLE
No way to specify eunit --dirs in config

### ISSUE THREAD

**Issue by agx** [rebar/rebar#627]
Hi,
There doesn't seem to be a way to give the equivalent of

  rebar3 eunit --dir foo,bar,src

in the rebar.conf i.e. I don't want to pass foo,bar,src on the command line but have it be the default patch for eunit to search for tests.

**Comment by lrascao** [comment]
Could you please clarify if this related with rebar3 or rebar2?

**Comment by agx** [comment]
On Tue, Nov 08, 2016 at 09:35:05AM -0800, Luis Rascão wrote:
> Could you please clarify if this related with rebar3 or rebar2?

rebar3

**Comment by lrascao** [comment]
ok, you probably want to report this on the rebar3 page then (https://github.com/erlang/rebar3)

**Comment by agx** [comment]
Oh dear - no idea how i ended up in the rebar2 tracker, sorry for the noise.

**Comment by lrascao** [comment]
no problem
