### ISSUE TITLE
rebar bootstrap fail

### ISSUE THREAD

**Issue by sugus-seu** [rebar/rebar#629]
rebar -V: rebar 2.6.0 18 20150906_075813 git 2.6.0-24-g2941760
Erlang/OTP 18 [erts-7.0] [source] [64-bit]

![image](https://cloud.githubusercontent.com/assets/10327864/21418493/96865ea4-c85c-11e6-9fe7-e5c920af040e.png)

how to fix?

**Comment by tuncer** [comment]
This has been fixed on 2015-09-11 in commit e025430da864374c16a9c59f0c33fd8438213294 and has been part of a couple releases since.

**Comment by tuncer** [comment]
Like I said, this has been resolved a long time ago in an older release. Therefore, this ticket can be closed as RESOLVED-FIXED.
