### ISSUE TITLE
function_clause error

### ISSUE THREAD

**Issue by mohnqwerty** [rebar/rebar#634]
hi 
please help me fix this
Uncaught error in rebar_core: {'EXIT',
                               {function_clause,
                                [{rebar_neotoma_compiler,info,
                                  [help,clean],
                                  [{file,"src/rebar_neotoma_compiler.erl"},
                                   {line,80}]},
                                 {rebar_core,'-help/2-fun-0-',2,
                                  [{file,"src/rebar_core.erl"},{line,63}]},
                                 {lists,foreach,2,
                                  [{file,"lists.erl"},{line,1338}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,759}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_em,1,[]},
                                 {init,do_boot,3,[]}]}}

**Comment by tuncer** [comment]
Fixed in #636.
