### ISSUE TITLE
Failed to generate 'relup'

### ISSUE THREAD

**Issue by parmar7725274** [rebar/rebar#647]
Hello everyone,

I have the project hosted on SVN. I want to generate relup file. Here is Details of issue i'm facing.

Project Directory structure, (Hope It is clear to everyone :) )

**/erl_experiment/**
------------------  **trunk/**
------------------  **branches/**
----------------------------------rel_v0_1_0/
-----------------------------------------------_{Source Code}_
----------------------------------rel_v0_2_0/
-----------------------------------------------_{Source Code}_
------------------  **tags/**

I'm able to generate appup file successfully using plugins [rebar3_appup_plugin]( https://github.com/lrascao/rebar3_appup_plugin.git) and command is (being in branch _rel_v0_2_0_), 

`./rebar3 appup generate --previous /home/user/svn/erl_experiment/branches/rel_v0_1_0/_build/default/rel/erl_experiment/`

And To generate relup i'm using the command (being in branch _rel_v0_2_0_),

`./rebar3 relup --lib-dir /home/user/svn/erl_experiment/branches/rel_v0_1_0/_build/default/ --path /home/user/svn/erl_experiment/branches/rel_v0_1_0/_build/default/lib`

And getting following error :
_
...
===> systools:make_relup("/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/releases/0.2.0/erl_experiment", "/home/user/svn/erl_experiment/branches/rel_v0_1_0/_build/default/rel/erl_experiment/releases/0.1.0/erl_experiment", "/home/user/svn/erl_experiment/branches/rel_v0_1_0/_build/default/rel/erl_experiment/releases/0.1.0/erl_experiment", [{outdir, "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment"},
 {path, ["/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/kernel-5.3/ebin", "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/stdlib-3.4/ebin", "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/sasl-3.0.4/ebin", "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/erl_experiment-0.2.0/ebin", **"/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/erl_experiment-0.1.0/ebin"**, "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/sasl-3.0.4/ebin", "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/stdlib-3.4/ebin", "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/kernel-5.3/ebin"]},silent])
===> Provider (relup) failed with: {error,
                                           {rlx_prv_relup,
                                            {relup_script_generation_error,
                                             systools_make,
                                             [{error_reading,
                                               {erl_experiment,
                                                {no_valid_version,
                                                 {{"should be","0.1.0"},
                                                  {"found file",
                                                   "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/erl_experiment-0.2.0/ebin/erl_experiment.app",
                                                   "0.2.0"}}}}}]}}}
===> Errors generating relup 
          erl_experiment: No valid version ("0.1.0") of .app file found. Found file "/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/erl_experiment-0.2.0/ebin/erl_experiment.app" with version "0.2.0"_

I'm Suspecting Following 4th arg PATH **_"/home/user/svn/erl_experiment/branches/rel_v0_2_0/_build/default/rel/erl_experiment/lib/erl_experiment-0.1.0/ebin"_** in of function call **systools:make_relup/4** which is wrong. it should be **_"/home/user/svn/erl_experiment/branches/rel_v0_1_0/_build/default/rel/erl_experiment/lib/erl_experiment-0.1.0/ebin"_**.

Does anyone tell why? 
Is there any way to give correct path explicitly ?

I have attached log for further reference. [relup_log.txt](https://github.com/rebar/rebar/files/1775177/relup_log.txt)

Here is a SVN repo I'm experimenting with [erl_experiment](https://svn.riouxsvn.com/erl_experiment), If anyone wants to try it :)

regards,
Prakash

**Comment by lrascao** [comment]
maybe you'd like instead to try out rebar3, this version has been deprecated and there's not a lot of support expected out of it
