### ISSUE TITLE
config include path doesn't effect on recursion directory

### ISSUE THREAD

**Issue by haoxianhan** [rebar/rebar#648]
I have project structure like:
![image](https://user-images.githubusercontent.com/3611408/37899644-b34f02c6-311e-11e8-9521-2d84c5501044.png)
rebar.config set `{erl_opts, [{i, "include"}]}.`
when I change a.hrl, compiler doesn't recompile the erl files which included the a.hrl .

**Comment by tuncer** [comment]
rebar has been superseded by rebar3, and as a consequence this repo is scheduled/supposed to be [archived](https://blog.github.com/2017-11-08-archiving-repositories/). Sorry for the inconvenience of the repo appearing to be active.

/cc @dizzyd @jaredmorrow @lrascao

**Comment by haoxianhan** [comment]
thinks, new project has change to rebar3.
